### ISSUE TITLE
menus.py fails

### ISSUE THREAD

**Issue by petkostas** [divio/django-cms#3343]
Following the documentation (http://docs.django-cms.org/en/latest/extending_cms/app_integration.html#apphook-menus)

I created a menus.py file in my app, yet I experienced the following awkward behavior:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/vagrant/.virtualenvs/zita/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/home/vagrant/.virtualenvs/zita/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/vagrant/.virtualenvs/zita/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
    mw_instance = mw_class()
  File "/home/vagrant/.virtualenvs/zita/local/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/home/vagrant/.virtualenvs/zita/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/.virtualenvs/zita/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/vagrant/.virtualenvs/zita/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/python-projects/zita/zita/zita/urls.py", line 14, in <module>
    url(r'^', include('cms.urls')),
  File "/home/vagrant/.virtualenvs/zita/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/vagrant/.virtualenvs/zita/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/vagrant/.virtualenvs/zita/local/lib/python2.7/site-packages/cms/urls.py", line 18, in <module>
    if apphook_pool.get_apphooks():
  File "/home/vagrant/.virtualenvs/zita/local/lib/python2.7/site-packages/cms/apphook_pool.py", line 63, in get_apphooks
    self.discover_apps()
  File "/home/vagrant/.virtualenvs/zita/local/lib/python2.7/site-packages/cms/apphook_pool.py", line 55, in discover_apps
    load('cms_app')
  File "/home/vagrant/.virtualenvs/zita/local/lib/python2.7/site-packages/cms/utils/django_load.py", line 56, in load
    get_module(app, modname, verbose, failfast)
  File "/home/vagrant/.virtualenvs/zita/local/lib/python2.7/site-packages/cms/utils/django_load.py", line 40, in get_module
    module = import_module(module_name)
  File "/home/vagrant/.virtualenvs/zita/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/python-projects/zita/zita/products/cms_app.py", line 4, in <module>
    from products.menus import ProductCategoryMenu
  File "/python-projects/zita/zita/products/menus.py", line 1, in <module>
    from menus.base import NavigationNode
ImportError: No module named base
```

My menus.py:
```
from menus.base import NavigationNode
from menus.menu_pool import menu_pool
from django.utils.translation import ugettext_lazy as _
from cms.menu_bases import CMSAttachMenu
from products.models import ProductCategory

class ProductCategoryMenu(CMSAttachMenu):

    name = _("test menu")

    def get_nodes(self, request):
        nodes = []
        for category in ProductCategory.objects.all().order_by("tree_id", "lft"):
            node = NavigationNode(
                category.name,
                category.get_absolute_url(),
                category.pk,
                category.parent_id
            )
            nodes.append(node)
        return nodes

menu_pool.register_menu(ProductCategoryMenu)
```

My cms_app.py:
```
from cms.app_base import CMSApp
from cms.apphook_pool import apphook_pool
from django.utils.translation import ugettext_lazy as _
from products.menus import ProductCategoryMenu

class ProductsAppHook(CMSApp):
    name = _("Products")
    urls = ["products.urls"]
    menus = [ProductCategoryMenu]

apphook_pool.register(ProductsAppHook)
```

Changing the name of the file from menus.py to something like cms_menus.py removes the above exception.
versions:
```
django-cms==3.0.3
Django==1.6.5
```

**Comment by FinalAngel** [comment]
closed in favour of https://github.com/divio/django-cms/issues/4597, feel free to continue the conversation here

**Comment by czpython** [comment]
Menus will be moved into cms app as per #5112
