### ISSUE TITLE
Error when trying to restore from history

### ISSUE THREAD

**Issue by petzlux** [divio/django-cms#3358]
When trying to restore from history, I get the following error:

````AttributeError: 'NoneType' object has no attribute 'tree_id'````

I am using Django CMS 3.0.3 

````
Traceback (most recent call last):

  File "/srv/env-master/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/srv/env-master/lib/python2.6/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)

  File "/srv/env-master/lib/python2.6/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)

  File "/srv/env-master/lib/python2.6/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)

  File "/srv/env-master/lib/python2.6/site-packages/reversion/revisions.py", line 300, in do_revision_context
    return func(*args, **kwargs)

  File "/srv/env-master/lib/python2.6/site-packages/cms/admin/pageadmin.py", line 748, in revision_view
    response = super(PageAdmin, self).revision_view(request, object_id, version_id, extra_context)

  File "/srv/env-master/lib/python2.6/site-packages/django/db/transaction.py", line 431, in inner
    return func(*args, **kwargs)

  File "/srv/env-master/lib/python2.6/site-packages/reversion/admin.py", line 406, in revision_view
    return self.render_revision_form(request, obj, version, context, revert=True)

  File "/srv/env-master/lib/python2.6/site-packages/cms/admin/pageadmin.py", line 772, in render_revision_form
    return super(PageAdmin, self).render_revision_form(request, obj, version, context, revert, recover)

  File "/srv/env-master/lib/python2.6/site-packages/reversion/admin.py", line 292, in render_revision_form
    self.save_model(request, new_object, form, change=True)

  File "/srv/env-master/lib/python2.6/site-packages/cms/admin/pageadmin.py", line 209, in save_model
    revert_plugins(request, obj.version.pk, obj)

  File "/srv/env-master/lib/python2.6/site-packages/cms/admin/views.py", line 52, in revert_plugins
    p.save()

  File "/srv/env-master/lib/python2.6/site-packages/cms/models/pluginmodel.py", line 243, in save
    super(CMSPlugin, self).save()

  File "/srv/env-master/lib/python2.6/site-packages/mptt/models.py", line 782, in save
    getattr(self, opts.tree_id_attr) != getattr(parent, opts.tree_id_attr) or

AttributeError: 'NoneType' object has no attribute 'tree_id'
````

**Comment by yakky** [comment]
@petzlux Does this still happens in latest 3.0.12?

**Comment by FinalAngel** [comment]
This has been fixed
