### ISSUE TITLE
Djangocms-installer crashes when creating new project.

### ISSUE THREAD

**Issue by holms** [divio/django-cms#3764]
@yakky You clearly get me wrong.

I've got a crash when creating new project, and it also removes PARENT directory, not current one. It means. Even if you want to remove parent directory for some reason please fix a crash, cause I can't even create a project. What's wrong with this community, do you even read my text in previous issue?

```
cd ~/
mkdir myproject
cd myproject
djangocms -p . zavifoto
*crash*
ls ~/
<no files>
```

Details bellow:
---------------------

I've been doing exactly as docs stated, and my whole directory been destroyed. Before that I've tried this in home directory, and all files were destroyed there too with this crash.

```
mkdir zavifoto
cd zavifoto
virtualenv .
source bin/activate
pip install djangocms-installer
```
```
(zavifoto)django@zavifoto:~/zavifoto$ djangocms -p . zavifoto
Database configuration (in URL format) [default sqlite://localhost/project.db]:
django CMS version (choices: 2.4, 3.0, stable, develop) [default stable]:
Django version (choices: 1.4, 1.5, 1.6, 1.7, stable) [default stable]: 1.7
Activate Django I18N / L10N setting (choices: yes, no) [default yes]:
Install and configure reversion support (choices: yes, no) [default yes]:
Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: lt,en,ru
Optional default time zone [default America/Chicago]: Europe/Vilnius
Activate Django timezone support (choices: yes, no) [default yes]: yes
Activate CMS permission management (choices: yes, no) [default yes]:
Use Twitter Bootstrap Theme (choices: yes, no) [default no]: yes
Use custom template set [default no]:
Load a starting page with examples after installation. Choose "no" if you use a custom template set. (choices: yes, no) [default no]: yes
Traceback (most recent call last):
  File "/home/django/zavifoto/bin/djangocms", line 11, in <module>
  File "/home/django/zavifoto/local/lib/python2.7/site-packages/djangocms_installer/main.py", line 47, in execute
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 22] Invalid argument: '.'
```

This is the latest ubuntu instance on digital ocean.

```
(zavifoto)django@zavifoto:~/zavifoto$ uname -a
Linux zavifoto 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yakky** [comment]
This is related to nephila/djangocms-installer, and should be opened in that repository.
This should be fixed in 0.7.1, anyway
