### ISSUE TITLE
Long usernames in swappable user model result in insert error for cms_page.Page

### ISSUE THREAD

**Issue by jesselegg** [divio/django-cms#3938]
I am using Django CMS with a swappable user model. My user model allows for long-ish usernames. When my username is greater than 70 characters, I am no longer able to save CMS pages because of the exception below. This occurs while trying to insert the long username into the `created_by` field. That field is `max_length=70`. It should probably truncate the username in cases where it exceeds this length. When I reduce my username to length < 70, I no longer receive an error on `Page` save.

```
Internal Server Error: /admin/cms/page/add/
Traceback (most recent call last):
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.DataError: value too long for type character varying(70)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 583, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 206, in inner
    return view(request, *args, **kwargs)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/cms/admin/pageadmin.py", line 406, in add_view
    return super(PageAdmin, self).add_view(request, form_url, extra_context=extra_context)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1453, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1404, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/cms/admin/pageadmin.py", line 206, in save_model
    obj.save()
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/cms/models/pagemodel.py", line 457, in save
    super(Page, self).save(**kwargs)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/mptt/models.py", line 838, in save
    super(MPTTModel, self).save(*args, **kwargs)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/cms/models/pagemodel.py", line 475, in save_base
    ret = super(Page, self).save_base(*args, **kwargs)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/flyweb/www/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(70)```

**Comment by yakky** [comment]
@mkoistinen @ojii how about having a longer field and cut the username at that length to be sure that this won't happen? it's just an informative field, after all

**Comment by mkoistinen** [comment]
+1

**Comment by ojii** [comment]
+1 set to ``255`` and truncate if too long (maybe change it to ``verylongusername...(id=11121)`` or something similar.

**Comment by yakky** [comment]
+1

**Comment by vad** [comment]
there should be the same problem with the `Page.changed_by` field
