### ISSUE TITLE
Broken logging call in pagemodel.py

### ISSUE THREAD

**Issue by timgraham** [divio/django-cms#3962]
`Logger.warn('foo')` results in the following traceback on Python 3:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: warn() missing 1 required positional argument: 'msg'
```
or this traceback on Python 2:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unbound method warning() must be called with Logger instance as first argument (got str instance instead)
```
https://github.com/divio/django-cms/blob/0055edadb481233eef180aba22a5fec875817d45/cms/models/pagemodel.py#L190

**Comment by yakky** [comment]
@mkoistinen could you backport #3848 to support ?
