### ISSUE TITLE
3.2 Installer does not work with Python 3

### ISSUE THREAD

**Issue by jkessel** [divio/django-cms#3983]
I tried to run the installer on Debian 7 with Python 3.2.3 and am getting the following error message

---

(env)jkessel@debian:~/djangoCMS$ vim /home/jkessel/djangoCMS/env/lib/python3.2/site-packages/djangocms_installer/config/\__init\__.py
(env)jkessel@debian:~/djangoCMS$ djangocms -p my_demo
Traceback (most recent call last):
  File "/home/jkessel/djangoCMS/env/bin/djangocms", line 7, in <module>
    from djangocms_installer.main import execute
  File "/home/jkessel/djangoCMS/env/lib/python3.2/site-packages/djangocms_installer/main.py", line 8, in <module>
    from . import config, django, install
  File "/home/jkessel/djangoCMS/env/lib/python3.2/site-packages/djangocms_installer/config/\__init\__.py", line 101
    sys.stderr.write(**u**"Project name '%s' is not a valid app name, "
                                                                  ^

---

Looks like Python 3 does not like the unicode helper '**u**' in front of each line.
Another documentation can be found here:
http://stackoverflow.com/questions/29295077/invalid-app-name-django-cms

**Comment by yakky** [comment]
Python 3.2 is not supported by django-cms  and djangocms-installer, you must upgrade to python 3.3
