### ISSUE TITLE
Cannot publish pages anymore since 3.1

### ISSUE THREAD

**Issue by sephii** [divio/django-cms#4074]
After upgrading to 3.1 I'm unable to publish pages. I get a 500 error with the following trace:

```
Traceback (most recent call last):
  File "/home/vagrant/env/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return self.application(environ, start_response)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    response = self.get_response(request)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 199, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/vagrant/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 236, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/vagrant/env/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 206, in inner
    return view(request, *args, **kwargs)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/vagrant/env/lib/python2.7/site-packages/reversion/revisions.py", line 297, in do_revision_context
    return func(*args, **kwargs)
  File "/home/vagrant/env/lib/python2.7/site-packages/cms/admin/pageadmin.py", line 956, in publish_page
    published = page.publish(language)
  File "/home/vagrant/env/lib/python2.7/site-packages/cms/models/pagemodel.py", line 621, in publish
    self.save()
  File "/home/vagrant/env/lib/python2.7/site-packages/cms/models/pagemodel.py", line 492, in save
    super(Page, self).save(**kwargs)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/vagrant/env/lib/python2.7/site-packages/cms/models/pagemodel.py", line 507, in save_base
    return super(Page, self).save_base(*args, **kwargs)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _save_table
    forced_update)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/db/models/base.py", line 723, in _do_update
    return filtered._update(values) > 0
  File "/home/vagrant/env/lib/python2.7/site-packages/django/db/models/query.py", line 600, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1004, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/env/lib/python2.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 159, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/home/vagrant/env/lib/python2.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 101, in _record
    return method(sql, params)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/vagrant/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "cms_page_path_518270318703c18f_uniq"
DETAIL:  Key (path)=(0005) already exists.
```

The weird thing is that if I dump the query and the parameters, I get this:

```
>>> sql
u'UPDATE "cms_page" SET "path" = %s, "depth" = %s, "numchild" = %s, "created_by" = %s, "changed_by" = %s, "parent_id" = NULL, "creation_date" = %s, "changed_date" = %s, "publication_date" = %s, "publication_end_date" = NULL, "in_navigation" = %s, "soft_root" = %s, "reverse_id" = NULL, "navigation_extenders" = NULL, "template" = %s, "site_id" = %s, "login_required" = %s, "limit_visibility_in_menu" = NULL, "is_home" = %s, "application_urls" = NULL, "application_namespace" = NULL, "publisher_is_draft" = %s, "publisher_public_id" = %s, "languages" = %s, "revision_id" = %s, "xframe_options" = %s WHERE "cms_page"."id" = %s'  
>>> params
(u'0005', 1, 0, u'foo', u'bar', u'2015-04-13 17:11:56.884334+00:00', u'2015-04-28 09:04:05.957800+00:00', u'2015-04-27 20:47:06.971613+00:00',   )
```

And if I run the query manually in a shell, the query succeeds. Maybe that's related to a transaction or something like that?

**Comment by sephii** [comment]
Running `./manage.py cms fix-tree` fixed the issue. Not sure why though. I'll reopen the issue if it persists.

**Comment by creimers** [comment]
`./manage.py cms fix-tree` also fixed this problem for me.
