### ISSUE TITLE
Two sites, one database: delete_orphaned_plugins finds other sites plugins and can't delete them because of foreignkey constraints

### ISSUE THREAD

**Issue by boydjohnson** [divio/django-cms#4250]
We have two sites using django.contrib.sites with a shared database and in anticipation of upgrading to django-cms 3.1.2 I ran manage.py cms delete_orphaned_plugins on our development environment for app 2 which has 0 plugins currently and it said there were 126 uninstalled plugins (I think from the other site) but ultimately couldn't delete them because of foreignkey constraints.  Is there something to pass to the command to check that it is only looking at the current site?

Here is the stack trace:
```You have requested to delete any instances of uninstalled plugins and unsaved plugin instances.
There are 126 uninstalled plugins and 0 unsaved_plugins.
Are you sure you want to do this?
Type 'yes' to continue, or 'no' to cancel: yes
... deleting any instances of uninstalled plugins and unsaved plugin instances
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/cms/management/commands/subcommands/base.py", line 24, in handle
    handle_command.handle(*args[1:], **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/dist-packages/cms/management/commands/subcommands/delete_orphaned_plugins.py", line 45, in handle_noargs
    instance.delete()
  File "/usr/local/lib/python2.7/dist-packages/cms/models/pluginmodel.py", line 467, in delete
    super(CMSPlugin, self).delete(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mptt/models.py", line 864, in delete
    super(MPTTModel, self).delete(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 739, in delete
    collector.delete()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py", line 284, in delete
    sender=model, instance=obj, using=self.using
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 339, in __exit__
    connection.commit()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 176, in commit
    self._commit()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 145, in _commit
    return self.connection.commit()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 145, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: update or delete on table "cms_cmsplugin" violates foreign key constraint "cms_custo_cmsplugin_ptr_id_29d26ee24934e6fb_fk_cms_cmsplugin_id" on table "cms_custom_accordionitem"
DETAIL:  Key (id)=(256) is still referenced from table "cms_custom_accordionitem".```

**Comment by yakky** [comment]
Sites should share not only the database, but also the codebase, otherwise ``delete_orphaned_plugins`` can't correctly detects installed plugins. From your report I can't understand if sites shares both

**Comment by boydjohnson** [comment]
Thanks @yakky, in our project we have a parent child relationship between the code bases where one site gets pip installed into the other and then some but not all of the apps are installed via installed apps in the settings.

**Comment by yakky** [comment]
@boydjohnson this is not supported by django CMS which assumes that all the sites share the same codebase and configuration

**Comment by boydjohnson** [comment]
If anyone is coming to this with the same issue, I added the other site's app that had the plugins to installed apps in the settings when I ./manage.py cms delete_orphaned_plugins and then took it out. I also had to add the plugin templates directory to the template dirs in the settings.

**Comment by yakky** [comment]
@boydjohnson Thanks for sharing  this.
Closing now
