### ISSUE TITLE
NoneType issue in downcast_plugins after creating a new plugin instance

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#4280]
I've just created a new plugin and after saving the very first instance of it I'm getting an error from `downcast_plugins`;

```
        for instance in plugin_qs:
            plugin_lookup[instance.pk] = instance
```

At this point `instance` is None but when it's called by `plugins = downcast_plugins(plugins, non_fallback_phs)` plugins is defined as a list of my new plugin instance by itself.

I don't think there's anything particularly unusual about my plugin;

```python
class CampaignSignupPlugin(CMSPluginBase):
    name = _('Newsletter signup plugin')
    model = Signup
    render_template = 'newsletter/signup.html'

    def render(self, context, instance, placeholder):
        request = context['request']
        if request.POST:
            form = SignupForm(request.POST)
            context.update({
                'form': form,
                'form_valid': form.is_valid(),
                'instance': instance,
            })
            return context

        context.update(
            {
                'form': SignupForm(
                    initial={
                        'campaign_id_1': instance.campaign_id_1,
                        'campaign_id_2': instance.campaign_id_2,
                        'campaign_id_3': instance.campaign_id_3,
                    }
                ),
                'instance': instance,
            }
        )
        return context
```

Having said that, I've ran `delete_orphaned_plugins` to try to clean up any issues and there is 1 plugin which can't be deleted because of a `NoneType` issue, so are the two related?

```bash
You have requested to delete any instances of uninstalled plugins and empty plugin instances.
There are 0 uninstalled plugins and 1 empty plugins.
Are you sure you want to do this?
Type 'yes' to continue, or 'no' to cancel: yes
... deleting any instances of uninstalled plugins and empty plugin instances
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/mwalker/Sites/proj/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/mwalker/Sites/proj/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/mwalker/Sites/proj/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/mwalker/Sites/proj/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/mwalker/Sites/proj/lib/python2.7/site-packages/cms/management/commands/subcommands/base.py", line 24, in handle
    handle_command.handle(*args[1:], **options)
  File "/Users/mwalker/Sites/proj/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/Users/mwalker/Sites/proj/lib/python2.7/site-packages/cms/management/commands/subcommands/delete_orphaned_plugins.py", line 48, in handle_noargs
    instance.delete()
  File "/Users/mwalker/Sites/proj/lib/python2.7/site-packages/cms/models/pluginmodel.py", line 458, in delete
    super(CMSPlugin, self).delete(*args, **kwargs)
  File "/Users/mwalker/Sites/proj/lib/python2.7/site-packages/treebeard/models.py", line 506, in delete
    self.__class__.objects.filter(pk=self.pk).delete()
  File "/Users/mwalker/Sites/proj/lib/python2.7/site-packages/treebeard/mp_tree.py", line 98, in delete
    super(MP_NodeQuerySet, qset).delete()
  File "/Users/mwalker/Sites/proj/lib/python2.7/site-packages/django/db/models/query.py", line 556, in delete
    collector.collect(del_query)
  File "/Users/mwalker/Sites/proj/lib/python2.7/site-packages/django/db/models/deletion.py", line 199, in collect
    field.rel.on_delete(self, field, sub_objs, self.using)
  File "/Users/mwalker/Sites/proj/lib/python2.7/site-packages/django/db/models/deletion.py", line 17, in CASCADE
    source_attr=field.name, nullable=field.null)
  File "/Users/mwalker/Sites/proj/lib/python2.7/site-packages/django/db/models/deletion.py", line 168, in collect
    reverse_dependency=reverse_dependency)
  File "/Users/mwalker/Sites/proj/lib/python2.7/site-packages/django/db/models/deletion.py", line 95, in add
    source._meta.concrete_model, set()).add(model._meta.concrete_model)
AttributeError: type object 'NoneType' has no attribute '_meta'
```

**Comment by yakky** [comment]
@marksweb how about the ``Signup`` model?

**Comment by marksweb** [comment]
Sure @yakky;

```python
class Signup(CMSPlugin):
    title_1 = models.CharField(
        _("Title"),
        max_length=255,
        blank=False,
    )
    campaign_id_1 = models.CharField(
        max_length=255,
        blank=False,
    )
    campaign_desc_1 = models.TextField()
    title_2 = models.CharField(
        _("Title"),
        max_length=255,
        blank=True,
        null=True,
    )
    campaign_id_2 = models.CharField(
        max_length=255,
        blank=True,
        null=True,
    )
    campaign_desc_2 = models.TextField(
        blank=True,
        null=True,
    )
    title_3 = models.CharField(
        _("Title"),
        max_length=255,
        blank=True,
        null=True,
    )
    campaign_id_3 = models.CharField(
        max_length=255,
        blank=True,
        null=True,
    )
    campaign_desc_3 = models.TextField(
        blank=True,
        null=True,
    )
    objects = CachedManager(cache_fields=['id'])

    class Meta:
        verbose_name_plural = "Newsletter signup"
        app_label = "djangocms_newsletter"
```

**Comment by marksweb** [comment]
I've taken out the cached manager & it works, so this must be a problem with our in house caching app.

I'll probably close this, as I can't imagine it's a CMS issue now.

**Comment by yakky** [comment]
Thanks for the update. Feel free to reopen this if you feel the CMS is involved
