### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_meta' in  migration process

### ISSUE THREAD

**Issue by linevich** [divio/django-cms#4350]
I'm trying to add field darken_image to existing model Post.
models.py
```
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from cms.models.fields import PlaceholderField
from django.utils.translation import gettext_lazy as _
from taggit.managers import TaggableManager
from cms.models.pluginmodel import CMSPlugin
from mptt.models import MPTTModel
from filer.fields.image import FilerImageField

BOOK_MARK = enumerate((0, 1, 2, 3, 4, 5))


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(is_draft=False)


class Post(models.Model):
    """
    Default post model
    """
    title = models.CharField(
        verbose_name=_(u"Title"),
        max_length=100,
        blank=True,
        null=True,
        default=_(u"Untitled"),
    )
    content = PlaceholderField(
        slotname='post_content',
        verbose_name=_(u"Text"),
        blank=True,
        null=True,
    )
    preview_text = models.TextField(
        verbose_name=_(u"Preview Text"),
        blank=True,
        null=True,
    )
    date = models.DateTimeField(
        verbose_name=_(u"Date"),
        auto_now_add=True,
    )
    modified = models.DateTimeField(
        verbose_name=_(u"Updated"),
        auto_now=True,
    )
    is_draft = models.BooleanField(
        verbose_name=_(u"Draft"),
        default=True,
    )
    enable_comments = models.BooleanField(
        verbose_name=_(u"Allow comments"),
        default=True,
    )
    category = models.ManyToManyField(
        "Category",
        verbose_name=_(u"Category"),
        blank=True,
    )
    # tag = TaggableManager(
    #     verbose_name=_(u"Tags"),
    #     blank=True,
    # )
    export_to_twitter = models.BooleanField(
        verbose_name=_(u"Export to Twitter"),
        default=True,
    )
    export_google_plus = models.BooleanField(
        verbose_name=_(u"Export to Google+"),
        default=True,
    )
    slug = models.SlugField(
        verbose_name=_(u"Slug"),
        max_length=100,
        blank=True,
        null=True,
    )

    image = FilerImageField(
        verbose_name=_(u"Preview image"),
        blank=True,
        null=True,
    )
    darken_image = models.CharField(
        verbose_name=_(u"Darken preview image (in range 0.0 - 1.0)"),
        default="0.0",
        max_length=3,
        blank=True,
        null=True,
    )
    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = _(u"Post")
        verbose_name_plural = _(u"Posts")
        ordering = ['-date', ]


class Category(MPTTModel):
    title = models.CharField(
        verbose_name=_("Title"),
        max_length=100,
        blank=True,
        null=True,
        default=_(u"Untitled")
    )
    parent = models.ForeignKey(
        "self",
        verbose_name=_(u"Parent category"),
        default=None,
        blank=True,
        null=True,
    )
    slug = models.SlugField(
        verbose_name=_(u"URI"),
        max_length=100,
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category', args=[self.slug])

    class MPTTMeta:
        order_insertion_by = ['title']
        parent_attr = 'parent'

    class Meta:
        verbose_name = _(u"Category")
        verbose_name_plural = _(u"Categories")
        ordering = ('title',)


class ListOfAllPosts(CMSPlugin):
    """
    Store category data for left panel
    """
    pass

```
Traceback
```
  Rendering model states...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/linevich_net/.env/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/linevich_net/.env/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/linevich_net/.env/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/linevich_net/.env/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/linevich_net/.env/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/linevich_net/.env/lib/python3.4/site-packages/django/db/migrations/executor.py", line 104, in migrate
    state = migration.mutate_state(state, preserve=do_run)
  File "/home/linevich_net/.env/lib/python3.4/site-packages/django/db/migrations/migration.py", line 83, in mutate_state
    operation.state_forwards(self.app_label, new_state)
  File "/home/linevich_net/.env/lib/python3.4/site-packages/django/db/migrations/operations/fields.py", line 51, in state_forwards
    state.reload_model(app_label, self.model_name_lower)
  File "/home/linevich_net/.env/lib/python3.4/site-packages/django/db/migrations/state.py", line 100, in reload_model
    related_models = get_related_models_recursive(old_model)
  File "/home/linevich_net/.env/lib/python3.4/site-packages/django/db/migrations/state.py", line 57, in get_related_models_recursive
    rel_app_label, rel_model_name = rel_mod._meta.app_label, rel_mod._meta.model_name
AttributeError: 'NoneType' object has no attribute '_meta'
```
I've already try to do it with 3.1.2, support@3.1.x and @develop branches - the same result.
Also I've removed all migrations and try to repeat all step-by-step - the same result.

**Comment by yakky** [comment]
@linevich while an issue on 3.1.2, I cannot reproduce this on latest support/3.1.x. Also check latest filer (0.9.12)

**Comment by linevich** [comment]
@yakky Thanks a lot, filer upgrade fixed an issue.
