### ISSUE TITLE
djangocms-installer: CalledProcessError

### ISSUE THREAD

**Issue by sedrubal** [divio/django-cms#4653]
I tried to install djangocms with the **djangocms-installer** but it always failes. Tested on `fedora:22` and `ubuntu:14.04` with `python3` and `python2`. After answering the questions it takes some time and then this messages appear:

```python
Please wait while I install dependencies
Command "/srv/venv/bin/python3.4 -c "import setuptools, tokenize;__file__='/tmp/pip-build-ywunetca/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-dd_zxv3n-record/install-record.txt --single-version-externally-managed --compile --install-headers /srv/venv/include/site/python3.4/Pillow" failed with error code 1 in /tmp/pip-build-ywunetca/Pillow
Failure occurred. Do you want to cleanup by removing /srv/cms? [Y/N] y
Removing everything under /srv/cms
Traceback (most recent call last):
  File "/srv/venv/lib/python3.4/site-packages/djangocms_installer/main.py", line 33, in execute
    config_data.requirements, config_data.pip_options
  File "/srv/venv/lib/python3.4/site-packages/djangocms_installer/install/__init__.py", line 90, in requirements
    subprocess.check_call(['pip'] + args)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'install', '-q', 'django-cms<3.2', 'django-treebeard>=2.0', 'https://github.com/divio/djangocms-admin-style/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-column/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-flash/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-googlemap/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-inherit/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-link/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-style/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-text-ckeditor/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-file/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-picture/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-teaser/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-video/archive/master.zip?1446510328.1703925', 'Django<1.8', 'pytz', 'django-reversion>=1.8.2,<1.8.6', 'django-classy-tags>=0.3.4.1', 'html5lib', 'Pillow>=2.3', 'django-sekizai>=0.7', 'six']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/venv/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/srv/venv/lib/python3.4/site-packages/djangocms_installer/main.py", line 64, in execute
    'http://djangocms-installer.rtfd.org\n' % e).with_traceback(tb)
  File "/srv/venv/lib/python3.4/site-packages/djangocms_installer/main.py", line 33, in execute
    config_data.requirements, config_data.pip_options
  File "/srv/venv/lib/python3.4/site-packages/djangocms_installer/install/__init__.py", line 90, in requirements
    subprocess.check_call(['pip'] + args)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
OSError: Command '['pip', 'install', '-q', 'django-cms<3.2', 'django-treebeard>=2.0', 'https://github.com/divio/djangocms-admin-style/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-column/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-flash/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-googlemap/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-inherit/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-link/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-style/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-text-ckeditor/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-file/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-picture/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-teaser/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-video/archive/master.zip?1446510328.1703925', 'Django<1.8', 'pytz', 'django-reversion>=1.8.2,<1.8.6', 'django-classy-tags>=0.3.4.1', 'html5lib', 'Pillow>=2.3', 'django-sekizai>=0.7', 'six']' returned non-zero exit status 1
Documentation available at http://djangocms-installer.rtfd.org
```

**Comment by yakky** [comment]
Please open this on https://github.com/nephila/djangocms-installer
it looks like a connection error during package install, though

**Comment by sedrubal** [comment]
Oh I'm sorry. See nephila/djangocms-installer#215
