### ISSUE TITLE
Django 1.8.6 BadMigrationError

### ISSUE THREAD

**Issue by jeroenweustink** [divio/django-cms#4761]
When running migrations I get a the exception BadMigrationError, I think it's due to the fact that django-cms 3.2 still contains south_migrations. I'm not able to fix it even when I remove the south migrations.

```bash
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jeroen/Projects/cms/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/jeroen/Projects/cms/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jeroen/Projects/cms/venv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/jeroen/Projects/cms/venv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/jeroen/Projects/cms/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/jeroen/Projects/cms/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/jeroen/Projects/cms/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/Users/jeroen/Projects/cms/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 182, in build_graph
    self.load_disk()
  File "/Users/jeroen/Projects/cms/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 123, in load_disk
    "creating Django migrations." % app_config.label
django.db.migrations.loader.BadMigrationError: Migrated app 'cms' contains South migrations. Make sure all numbered South migrations are deleted prior to creating Django migrations.
```

**Comment by jeroenweustink** [comment]
Looks like the same issue as https://github.com/stefanfoulis/django-filer/issues/609.

**Comment by yakky** [comment]
@jeroenweustink we removed the broken wheelfile from pypi, it will come back with a 3.2.1 release
Thanks for reporting this

**Comment by jeroenweustink** [comment]
Once again, thanks @yakky

**Comment by yakky** [comment]
Closing this
