### ISSUE TITLE
DjangCMS 3.2 - Unable to upgrade to django 1.9: ImportError cms.templatetags.cms_admin': cannot import name Page

### ISSUE THREAD

**Issue by JoeJasinski** [divio/django-cms#4816]
Hi all, 

When trying upgrade to Django from 1.8.7 to 1.9 and django-reversion from 1.8.7 to 1.10.0, I get the following error when I migrate.  The *only* changes that I made was to upgrade these two packages.  Django CMS 3.2 was installed and running fine on Django 1.8. 

	(joejasinski)cortland:joejasinski jjasinski$ ./manage.py migrate
	Traceback (most recent call last):
	  File "./manage.py", line 10, in <module>
		execute_from_command_line(sys.argv)
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
		utility.execute()
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/core/management/__init__.py", line 324, in execute
		django.setup()
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
		apps.populate(settings.INSTALLED_APPS)
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
		app_config.import_models(all_models)
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
		self.models_module = import_module(models_module_name)
	  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
		__import__(name)
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/cms/models/__init__.py", line 3, in <module>
		from .pagemodel import *  # nopyflakes
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/cms/models/pagemodel.py", line 23, in <module>
		from cms.models.placeholdermodel import Placeholder
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/cms/models/placeholdermodel.py", line 13, in <module>
		from cms.utils.placeholder import PlaceholderNoAction, get_placeholder_conf
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/cms/utils/placeholder.py", line 21, in <module>
		from sekizai.helpers import get_varname, is_variable_extend_node, engines
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/sekizai/helpers.py", line 15, in <module>
		_FAKE_TEMPLATE = (namedtuple('Template', 'engine')(engines.all()[0]))
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/template/utils.py", line 110, in all
		return [self[alias] for alias in self]
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/template/utils.py", line 101, in __getitem__
		engine = engine_cls(params)
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/template/backends/django.py", line 31, in __init__
		options['libraries'] = self.get_templatetag_libraries(libraries)
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/template/backends/django.py", line 49, in get_templatetag_libraries
		libraries = get_installed_libraries()
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/template/backends/django.py", line 131, in get_installed_libraries
		for name in get_package_libraries(pkg):
	  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/template/backends/django.py", line 148, in get_package_libraries
		"trying to load '%s': %s" % (entry[1], e)
	django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'cms.templatetags.cms_admin': cannot import name Page

Below is the output of pip freeze. 

    beautifulsoup4==4.4.0
    dj-database-url==0.3.0
    Django==1.9
    django-classy-tags==0.6.2
    django-cms==3.2.0
    django-extensions==1.5.9
    django-formtools==1.0
    django-htmlmin==0.8.0
    django-nocaptcha-recaptcha==0.0.18
    django-reversion==1.10.0
    django-sekizai==0.8.2
    Django-Select2==4.3.1
    django-treebeard==3.0
    djangocms-admin-style==1.0.7
    djangocms-inherit==0.1
    djangocms-link==1.7.1
    -e git+https://github.com/JoeJasinski/djangocms-plain-text.git@7e98fd859acd44a996526928c92c9458b433f736#egg=djangocms_plain_text-master
    djangocms-snippet==1.7.1
    djangocms-teaser==0.2.0
    djangocms-text-ckeditor==2.8.0
    html5lib==0.999999
    Pillow==3.0.0
    psycopg2==2.6.1
    six==1.9.0
    sorl-thumbnail==12.3
    wheel==0.24.0

Excerpt from settings.py

    INSTALLED_APPS = (
		'django.contrib.auth',
		'django.contrib.contenttypes',
		'django.contrib.sessions',
		'django.contrib.sites',
		'django.contrib.messages',
		'django.contrib.staticfiles',
		'djangocms_admin_style',
		'django.contrib.admin',

		'nocaptcha_recaptcha',
		'cms',
		'treebeard',
		'menus',
		'sekizai',
		'reversion',
		'sorl.thumbnail',
		'django_extensions',

		'pagefeature',  # project module
		'contact_form',  # project module
		'photo_gallery.apps.PhotoConfig',  # project module
		'djangocms_inherit',
		'djangocms_teaser',
		'djangocms_link',
		'djangocms_snippet',
		'djangocms_text_ckeditor',
		'djangocms_plain_text',
    )

    MIGRATION_MODULES = {
	'djangocms_file': 'djangocms_file.migrations_django',
	'djangocms_flash': 'djangocms_flash.migrations_django',
	'djangocms_googlemap': 'djangocms_googlemap.migrations_django',
	'djangocms_inherit': 'djangocms_inherit.migrations_django',
	'djangocms_link': 'djangocms_link.migrations_django',
	'djangocms_picture': 'djangocms_picture.migrations_django',
	'djangocms_snippet': 'djangocms_snippet.migrations_django',
	'djangocms_teaser': 'djangocms_teaser.migrations_django',
	'djangocms_video': 'djangocms_video.migrations_django',
	'djangocms_text_ckeditor': 'djangocms_text_ckeditor.migrations',
    }

    TEMPLATES = [
		{
			'BACKEND': 'django.template.backends.django.DjangoTemplates',
			'DIRS': [os.path.join(PROJECT_DIR, 'templates')],
			'APP_DIRS': True,
			'OPTIONS': {
				'context_processors': [
					'django.contrib.auth.context_processors.auth',
					'django.contrib.messages.context_processors.messages',
					'django.core.context_processors.i18n',
					'django.core.context_processors.request',
					'django.core.context_processors.media',
					'django.core.context_processors.static',
					'sekizai.context_processors.sekizai',
					'cms.context_processors.cms_settings',
				],
			},
		},
    ]

Any thoughts on what this might be?

**Comment by yakky** [comment]
django CMS 3.2 does not support Django 1.9 (still)

**Comment by JoeJasinski** [comment]
Thanks for that info. I'll hold off on the upgrade.

**Comment by ccbndh** [comment]
+1

**Comment by yakky** [comment]
@ccbndh, @JoeJasinski could you test #4812 for Django 1.9 support?

**Comment by mkoistinen** [comment]
Should be closed by #4812
