### ISSUE TITLE
djangocms-placeholder-attr fails to install on python 3.4

### ISSUE THREAD

**Issue by rando305** [divio/django-cms#4825]
(Ops_python3) randy@TestSrv:~/PycharmProjects/Ops_python3$ which pip
/home/randy/PycharmProjects/Ops_python3/bin/pip
(Ops_python3) randy@TestSrv:~/PycharmProjects/Ops_python3$ pip install djangocms-placeholder-attr
Collecting djangocms-placeholder-attr
  Using cached djangocms-placeholder-attr-1.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/djangocms_placeholder_attr.egg-info
    writing top-level names to pip-egg-info/djangocms_placeholder_attr.egg-info/top_level.txt
    writing pip-egg-info/djangocms_placeholder_attr.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-wfdn4b93/djangocms-placeholder-attr/setup.py", line 34, in <module>
        zip_safe=False,
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "<string>", line 14, in replacement_run
      File "/home/randy/PycharmProjects/Ops_python3/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 388, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/lib/python3.4/distutils/dist.py", line 1108, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/usr/lib/python3.4/distutils/dist.py", line 1129, in write_pkg_file
        long_desc = rfc822_escape(self.get_long_description())
      File "/usr/lib/python3.4/distutils/util.py", line 470, in rfc822_escape
        lines = header.split('\n')
    TypeError: 'str' does not support the buffer interface
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wfdn4b93/djangocms-placeholder-attr

I'm using ubuntu 12.04
python 3.4

**Comment by yakky** [comment]
You should file a bug in djangocms-placeholder-attr repository. It's not a plugin maintained by django cms team, so we can't do much to fix it
