### ISSUE TITLE
Cannot resolve bases - Dj 1.8.7, Dj-CMS 3.2.0

### ISSUE THREAD

**Issue by sedrubal** [divio/django-cms#4843]
I'm currently building [a new django-cms site](https://github.com/fau-fablab/website/) and so I often reinstalled the venv and so on and migrated the db and so on but suddenly it doesn't work anymore:
When I want to migrate the db (no matter if it's an existing or a new db) (sqlite3) it always fails:

```python
Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages, djangocms_admin_style, sitemaps, sekizai, fablab_website, djangocms_style, treebeard, djangocms_teaser
  Apply all migrations: djangocms_flash, djangocms_file, reversion, djangocms_inherit, sessions, admin, djangocms_column, sites, auth, djangocms_video, menus, contenttypes, djangocms_picture, djangocms_googlemap, djangocms_link, cms, djangocms_text_ckeditor
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/tmp/website/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/tmp/website/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/tmp/website/venv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/tmp/website/venv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/tmp/website/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/tmp/website/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 100, in migrate
    state.apps  # Render all real_apps -- performance critical
  File "/tmp/website/venv/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tmp/website/venv/lib/python2.7/site-packages/django/db/migrations/state.py", line 166, in apps
    return StateApps(self.real_apps, self.models)
  File "/tmp/website/venv/lib/python2.7/site-packages/django/db/migrations/state.py", line 232, in __init__
    self.render_multiple(list(models.values()) + self.real_models)
  File "/tmp/website/venv/lib/python2.7/site-packages/django/db/migrations/state.py", line 270, in render_multiple
    "for more" % (new_unrendered_models, get_docs_version())
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'djangocms_style.Style'>, <ModelState: 'djangocms_teaser.Teaser'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.8/topics/migrations/#dependencies for more
```

The settings are here: https://github.com/fau-fablab/website/blob/djangocms/djangocms/fablab_website/settings.py

And this are the packages installed in my venv:

```python
Django==1.8.7
django-appconf==1.0.1
django-classy-tags==0.7.0
django-cms==3.2.0
django-compressor==1.6
django-formtools==1.0
django-reversion==1.8.7
django-sass-processor==0.3.0
django-sekizai==0.9.0
Django-Select2==4.3.2
django-treebeard==3.0
djangocms-admin-style==1.0.7
djangocms-column==1.6.0
djangocms-file==0.2.0
djangocms-flash==0.3.0
djangocms-googlemap==0.4.0
djangocms-inherit==0.1.1
djangocms-link==1.7.1
djangocms-picture==0.2.0
djangocms-style==1.6.0
djangocms-teaser==0.2.0
djangocms-text-ckeditor==2.8.0
djangocms-video==0.2.0
html5lib==0.9999999
libsass==0.9.3
Pillow==3.0.0
pytz==2015.7
six==1.10.0
```

Running everything with `python2` didn't change anything.

**Comment by yakky** [comment]
Do you have  ``MIGRATION_MODULES``  set in ``settings.py``?

**Comment by sedrubal** [comment]
Thanks for your reply.

Yes, I added this:

```python
MIGRATION_MODULES = {
    'djangocms_style': 'djangocms_style.migrations_django',
    'djangocms_teaser': 'djangocms_teaser.migrations_django'
}
```

(You can see my config here: https://github.com/fau-fablab/website/blob/djangocms/djangocms/fablab_website/settings.py#L195)

**Comment by yakky** [comment]
``djangocms-teaser`` changed migration modules layout in ``0.2.0`` and ``djangocms-style`` in ``1.6.0``, so you need to remove those lines.
Probably those two new versions have been released after you create the first draft of your project and when you later recreated the virtualenv without pinning the package versions of the draft of the project

**Comment by sedrubal** [comment]
Oh, you're great :D have you a good tactic to prevent those issues? Is it a good idea to add a single version of each package to `requirements.txt`? Or is there a way to get informed about those changes?

**Comment by yakky** [comment]
Best option is usually is saving the output of ``pip freeze`` to the requirements file and use something like requires.io to check for updates
