### ISSUE TITLE
App Resolver not working in tests when using django 1.8

### ISSUE THREAD

**Issue by stephenpaulger** [divio/django-cms#4852]
I'm using django 1.8.7 and django-cms 3.1.4

In the setup of my tests pages are created with apphooks and in the tear downs they are removed. With Django 1.7 these tests were passing.

In tests after the first any requests that involve the app resolver fail with a traceback like this. If I re-order the tests they all pass provided they are the first test.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms/utils/decorators.py", line 12, in inner
    if page:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 225, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 365, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/cms/middleware/page.py", line 20, in <lambda>
    request.current_page = SimpleLazyObject(lambda: get_page(request))
  File "/usr/local/lib/python2.7/dist-packages/cms/middleware/page.py", line 14, in get_page
    request._current_page_cache = applications_page_check(request)
  File "/usr/local/lib/python2.7/dist-packages/cms/appresolver.py", line 54, in applications_page_check
    page = Page.objects.public().get(id=page_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Page matching query does not exist.
```

in appresolver.py the line 

```python
page_id = resolver.resolve_page_id(path)
```

`resolve_page_id(path)` always returns the same id, even if the page corresponding to that id has been deleted.

**Comment by stephenpaulger** [comment]
It looks like this may be because the server needs restarting after the app hooks are altered, which is mentioned in the documentation. I'm not sure why it worked with django 1.7 but willing to close this anyway.
