### ISSUE TITLE
unable to create a project

### ISSUE THREAD

**Issue by omriba** [divio/django-cms#4861]
Hey,

I am new to django CMS, I am trying to start a new project and
keep getting the following error after using
djangocms -f -p . my_site

Creating the projectFailure occurred. Do you want to cleanup by removing 

Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "...\Scripts\djangocms.exe\__main__.py", line 9, in <module>
  File "...\env\lib\site-packages\djangocms_installer\main.py", line 41, in execute
    django.setup_database(config_data)
  File "...\env\lib\site-packages\djangocms_installer\django\__init__.py", line 411, in setup_database
    env=env
  File "c:\python27\Lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\python27\Lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "c:\python27\Lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "c:\python27\Lib\subprocess.py", line 958, in _execute_child
    startupinfo)
TypeError: environment can only contain strings

any ideas ?

**Comment by yakky** [comment]
Issue in the installer, please check the referenced PR

**Comment by omriba** [comment]
great, thanks a lot!

**Comment by yakky** [comment]
@omriba could you test https://github.com/nephila/djangocms-installer/archive/feature/force_str_osenv.zip if fixes the issue for you?

**Comment by omriba** [comment]
@yakky 
its already solved using the link you gave me.
removing unicode_literals from the import
