### ISSUE TITLE
Exception during install

### ISSUE THREAD

**Issue by nielsole** [divio/django-cms#4978]
I was following the installation guide both in the [docs](http://docs.django-cms.org/en/stable/introduction/install.html) and the [readme](https://github.com/divio/django-cms).

Each time I ran into an exception when executing: `djangocms -f -p . mydemo`
```
Dependencies installed
Creating the project
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/my_user_account/dj-cms/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/my_user_account/dj-cms/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/my_user_account/dj-cms/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/my_user_account/dj-cms/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/my_user_account/dj-cms/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/my_user_account/dj-cms/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/my_user_account/dj-cms/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/home/my_user_account/dj-cms/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 191, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/my_user_account/dj-cms/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/home/my_user_account/dj-cms/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/my_user_account/dj-cms/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 162, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/my_user_account/dj-cms/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/home/my_user_account/dj-cms/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/home/my_user_account/dj-cms/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 114, in connect
    self.close_at = None if max_age is None else time.time() + max_age
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```

I tried replicating this on a different machine with the same result. I also tried Python 2.7.* and 3.*. Both machines are running Ubuntu 14.04 LTS.
The exception can be replicated by running `./manage.py migrate` after the failed install.

**Comment by nielsole** [comment]
Output of pip freeze:
```
cmsplugin-filer==1.0.1
dj-database-url==0.4.0
Django==1.8.9
django-appconf==1.0.1
django-classy-tags==0.7.1
django-cms==3.2.1
django-filer==1.1.1
django-formtools==1.0
django-mptt==0.8.0
django-polymorphic==0.8.1
django-reversion==1.8.7
django-sekizai==0.9.0
Django-Select2==4.3.2
django-treebeard==4.0
djangocms-admin-style==1.1.0
djangocms-column==1.6.0
djangocms-googlemap==0.4.0
djangocms-inherit==0.1.1
djangocms-installer==0.8.5
djangocms-link==1.7.1
djangocms-style==1.6.0
djangocms-text-ckeditor==2.8.1
easy-thumbnails==2.3
html5lib==0.9999999
Pillow==3.1.0
pytz==2015.7
six==1.10.0
tzlocal==1.2
Unidecode==0.4.19
wheel==0.26.0
```

**Comment by yakky** [comment]
@nielsole see nephila/djangocms-installer#235
This is due to a bug in the installer + new version of dj-database-url which has just been released.
A fix is due shortly

**Comment by nielsole** [comment]
Great, thanks!
