### ISSUE TITLE
[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]The object 'cms_cmsplugin_level_0ccc318d_check' is dependent on column 'level'. (5074) (SQLExecDirectW)

### ISSUE THREAD

**Issue by mkane848** [divio/django-cms#4987]
Attempting to run DjangoCMS 3.2.1 on Django 1.9.2 with django-pyodbc-azure 1.9.1.0 on a Windows 10 desktop to connect to my MS SQL server.

When attempting to migrate, I get the following traceback:

```
Operations to perform:
  Apply all migrations: djangocms_snippet, djangocms_text_ckeditor, djangocms_googlemap, cms, djangocms_link, filer, sites, easy_thumbnails, reversion, sessions, admin, contenttypes, djangocms_style, auth, djangocms_inherit, menus
Running migrations:
  Rendering model states... DONE
  Applying cms.0006_auto_20140924_1110...Traceback (most recent call last):
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\sql_server\pyodbc\base.py", line 537, in execute
    return self.cursor.execute(sql, params)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]The object 'cms_cmsplugin_level_0ccc318d_check' is dependent on column 'level'. (5074) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\core\management\base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\core\management\base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\core\management\commands\migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\db\migrations\executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\db\migrations\executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\db\migrations\executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\db\migrations\migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\db\migrations\operations\fields.py", line 121, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\sql_server\pyodbc\schema.py", line 593, in remove_field
    self.execute(sql)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\sql_server\pyodbc\schema.py", line 516, in execute
    cursor.execute(sql, params)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\mkane\Envs\mnet\lib\site-packages\sql_server\pyodbc\base.py", line 537, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]The object 'cms_cmsplugin_level_0ccc318d_check' is dependent on column 'level'. (5074) (SQLExecDirectW)")
```

I'm not exactly sure if this is an issue with djangoCMS or django-pyodbc-azure, so I apologize if this isn't something on your guys' end.

Thanks!

**Comment by mkane848** [comment]
Turned out to be on django-pyodbc-azure's end, a recent update fixed the issue
