### ISSUE TITLE
polymorphic module not found so cms not installing

### ISSUE THREAD

**Issue by shauntrick** [divio/django-cms#4997]
Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the project
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pratyush/Documents/djangocmsproject/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/pratyush/Documents/djangocmsproject/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/pratyush/Documents/djangocmsproject/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pratyush/Documents/djangocmsproject/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/pratyush/Documents/djangocmsproject/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pratyush/Documents/djangocmsproject/local/lib/python2.7/site-packages/filer/models/__init__.py", line 3, in <module>
    from filer.models.clipboardmodels import *  # flake8: noqa
  File "/home/pratyush/Documents/djangocmsproject/local/lib/python2.7/site-packages/filer/models/clipboardmodels.py", line 9, in <module>
    from filer.models import filemodels
  File "/home/pratyush/Documents/djangocmsproject/local/lib/python2.7/site-packages/filer/models/filemodels.py", line 19, in <module>
    from polymorphic import PolymorphicModel, PolymorphicManager
ImportError: No module named polymorphic
Failure occurred. Do you want to cleanup by removing /home/pratyush/Documents/djangocmsproject/app?  [Y/n]

**Comment by yakky** [comment]
could you open this on https://github.com/nephila/djangocms-installer?
It's the repository for the installer tool.
Could you also provide the pip freeze for the virtualenv and the option you provided to the installer (namely django and django cms versions)?
Thanks

**Comment by shauntrick** [comment]
Problem is solved actually virtualenv was using python 2 as default when i added python 3 to virtual env the project was created without any error 
I used the command virtualenv -p/usr/bin/python3 venv
