### ISSUE TITLE
cms.test.test_po.PoTest.test_po_sanity fails ~1 out of 6 times

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-cms#5046]
When I run this test locally, it fails roughly one out of six times:

```
./manage.py test cms.tests.test_po.PoTest.test_po_sanity
E
======================================================================
ERROR: test_po_sanity (cms.tests.test_po.PoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/app/cms/tests/test_po.py", line 61, in test_po_sanity
    ok, stderr = compile_messages()
  File "/usr/src/app/cms/tests/test_po.py", line 44, in compile_messages
    pipe = subprocess.Popen(bits, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

----------------------------------------------------------------------
Ran 1 test in 9.906s

FAILED
 (errors=1)
```

**Comment by stefanfoulis** [comment]
Turns out I did not have ``gettext`` installed, which brings the ``msgfmt`` command. Now the mystery is: why did the test sometimes pass anyway?

**Comment by stefanfoulis** [comment]
I'm not experiencing this error anymore and the missing ``gettext`` error was made clearer in #5047.
