### ISSUE TITLE
Django 1.9 import error

### ISSUE THREAD

**Issue by pratyushsharma** [divio/django-cms#5160]
Django (1.9.3)
django-cms (3.2.3)
Traceback (most recent call last):
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/template/utils.py", line 86, in __getitem__
    return self._engines[alias]
KeyError: 'django'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/template/backends/django.py", line 144, in get_package_libraries
    module = import_module(entry[1])
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/cms/templatetags/cms_tags.py", line 39, in <module>
    from sekizai.helpers import Watcher
ImportError: cannot import name 'Watcher'
During handling of the above exception, another exception occurred:
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'cms.templatetags.cms_tags': cannot import name 'Watcher'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/cms/models/__init__.py", line 8, in <module>
    from .placeholderpluginmodel import *  # nopyflakes
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/cms/models/placeholderpluginmodel.py", line 10, in <module>
    class PlaceholderReference(CMSPlugin):
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/cms/models/placeholderpluginmodel.py", line 12, in PlaceholderReference
    placeholder_ref = PlaceholderField(slotname='clipboard')
 File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/cms/models/fields.py", line 10, in __init__
    from cms.utils.placeholder import PlaceholderNoAction, validate_placeholder_name
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/cms/utils/placeholder.py", line 20, in <module>
    from sekizai.helpers import get_varname, is_variable_extend_node, engines
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/sekizai/helpers.py", line 15, in <module>
    _FAKE_TEMPLATE = (namedtuple('Template', 'engine')(engines.all()[0]))
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/template/utils.py", line 110, in all
    return [self[alias] for alias in self]
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/template/utils.py", line 110, in <listcomp>
    return [self[alias] for alias in self]
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/template/utils.py", line 101, in __getitem__
    engine = engine_cls(params)
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/template/backends/django.py", line 31, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/template/backends/django.py", line 49, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/template/backends/django.py", line 131, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/nitrous/code/Aws/sociafluence/venv/lib/python3.4/site-packages/django/template/backends/django.py", line 148, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'cms.templatetags.cms_tags': cannot import name 'Watcher'

**Comment by FinalAngel** [comment]
@pratyushsharma thanks for the report. Can you provide us with additional information on how you encountered that error, like:

- How did you install the CMS
- Your environment (OS, Setup etc.)
- Eventually your `pip freeze`

thanks!

**Comment by pratyushsharma** [comment]
Django==1.9.3
Django-Select2==4.3.2
Flask==0.10.1
Jinja2==2.8
MarkupSafe==0.23
Pillow==3.0.0
PyJWT==1.4.0
PyYAML==3.11
South==1.0.2
Unidecode==0.4.19
Werkzeug==0.11.3
Whoosh==2.7.0
argparse==1.4.0
arrow==0.7.0
-e git://github.com/pratyushsharma/aws-requests-auth.git@6491d145dbf9e241de5d7db920563f5fec3adef9#egg=aws_requests_auth-master
awsebcli==3.7.3
bbcode==1.0.22
beautifulsoup4==4.4.1
blessed==1.9.5
boto==2.38.0
boto3==1.3.0
botocore==1.4.1
cement==2.4.0
certifi==2015.11.20.1
cffi==1.5.2
chardet==2.3.0
click==5.1
cmsplugin-filer==0.10.1
colorama==0.3.3
cryptography==1.2.2
csscompressor==0.9.4
cssselect==0.9.1
defusedxml==0.4.1
django-annoying==0.8.7
django-appconf==1.0.1
django-bootstrap-form==3.2
django-braces==1.8.1
django-classy-tags==0.7.2
django-cms==3.2.3
django-compressor==2.0
django-countries==3.4.1
django-debug-panel==0.8.2
django-debug-toolbar==1.4
django-djconfig==0.4.0
```
django-extensions==1.6.1
django-facebook==6.0.3
django-filer==0.9.9
django-formtools==1.0
-e git://github.com/django-haystack/django-haystack.git@672ca9f295209c5c86a45845a25ae973036fa8e1#egg=django_haystack-origin/HEAD
django-infinite-scroll-pagination==0.1.3
django-mptt==0.6.1
django-oauth-toolkit==0.9.0
django-pgfields==1.4.4
django-polymorphic==0.9.1
django-redis-cache==1.6.5
django-registration-redux==1.4
django-rest-framework-social-oauth2==1.0.2
django-reversion==1.8.5

django-rq-dashboard==0.2.9
django-sekizai==0.8.2

django-simple-captcha==0.5.1
django-spirit==0.4.6
django-storages==1.4
django-taggit==0.17.3
django-taggit-serializer==0.1.5
django-treebeard==3.0
django-user-accounts==1.3.1
django-websocket-redis==0.4.6
djangocms-admin-style==0.2.2
djangocms-file==1.0
djangocms-flash==0.3.0
djangocms-googlemap==0.4.0
djangocms-inherit==0.1.1
djangocms-link==1.7.2
djangocms-picture==1.0.0
djangocms-teaser==0.2.0
djangocms-video==1.0.0
djangorestframework==3.3.2
djangorestframework-jwt==1.7.2
docker-py==1.1.0
dockerpty==0.3.4
docopt==0.6.2
docutils==0.12
drf-haystack==1.5.6
easy-thumbnails==2.3
eatiht==0.1.14
eight==0.3.3
elasticsearch==1.9.0
feedfinder2==0.0.4
feedparser==5.2.1
future==0.15.2
gevent==1.1.1
google-api-python-client==1.4.2
greenlet==0.4.9
gunicorn==19.1.1
html5lib==0.999
httplib2==0.9.2
idna==2.0
ipython==2.3.1
itsdangerous==0.24
jieba3k==0.35.1
jmespath==0.9.0
jsonfield==1.0.3
lxml==3.5.0
meld3==1.0.2
mistune==0.7.1
mock==1.3.0
ndg-httpsclient==0.4.0
newspaper3k==0.1.7
nltk==3.2
oauth2client==1.5.2
oauthlib==1.0.1
pathspec==0.3.3
pbr==1.8.1
pinax-theme-bootstrap==7.3.0
ply==3.8
psycopg2==2.5.4
pyOpenSSL==0.15.1
pyasn1==0.1.9
pyasn1-modules==0.0.8
-e git://github.com/hovel/pybbm.git@8fb3f807e8c60055836ab72727e749837bcebff6#egg=pybbm-origin/master
pycparser==2.14
pydot2==1.0.33
pyelasticsearch==1.4
pygraphviz==1.3.1
pyparsing==2.0.7
python-dateutil==2.4.2
python-instagram==1.3.2
python-rake==1.0.6
python-social-auth==0.2.14
python3-openid==3.0.9
pytils==0.3
pytz==2015.7
rcssmin==1.0.6
redis==2.10.5
requests==2.9.1
requests-oauthlib==0.6.1
rjsmin==1.0.12
rq==0.5.6
rq-dashboard==0.3.6
rq-scheduler==0.5.1
rsa==3.2.3
simplejson==3.8.1
six==1.10.0
slimit==0.8.1
sorl-thumbnail==12.4a1
sqlparse==0.1.19
texttable==0.8.4
tldextract==1.7.5
tweepy==3.5.0
uWSGI==2.0.12
unicode-slugify==0.1.3
uritemplate==0.6
urllib3==1.14
watchtower==0.2.0
wcwidth==0.1.6
websocket-client==0.35.0

```
OS Ubuntu 14.04.3 LTS
Manually installed cms using [http://docs.django-cms.org/en/latest/how_to/install.html](url)
```
INSTALLED_APPS =  (
    
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',

    'django.contrib.messages',

    'djangocms_admin_style',  # for the admin skin. You **must** add 'djangocms_admin_style' in the list **before** 'django.contrib.admin'.
    'django.contrib.admin',
    'django.contrib.sites',
    'redis_cache',
    'social.apps.django_app.default',
    ...
    
     'cms',  # django CMS itself
             'sekizai',  # for JavaScript and CSS management
     'treebeard',  # utilities for implementing a tree
     'menus',  # helper for model independent hierarchical website navigation
     'djangocms_file',
     'djangocms_flash',
     'djangocms_googlemap',
     'djangocms_inherit',
     'djangocms_picture',
     'djangocms_teaser',
     'djangocms_video',
     'djangocms_link',

)

MIDDLEWARE_CLASSES = (
     'cms.middleware.utils.ApphookReloadMiddleware',
    'debug_panel.middleware.DebugPanelMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pybb.middleware.PybbMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
     'cms.middleware.page.CurrentPageMiddleware',
     'cms.middleware.toolbar.ToolbarMiddleware',
     'cms.middleware.language.LanguageCookieMiddleware',

)
'context_processors': [

                'django.template.context_processors.request',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
                'django.contrib.auth.context_processors.auth',
                'django.core.context_processors.static',
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "django.contrib.messages.context_processors.messages"
                'pybb.context_processors.processor',
                'sekizai.context_processors.sekizai',
                 'cms.context_processors.cms_settings', 

            ],
```

**Comment by FinalAngel** [comment]
@mkoistinen @yakky @czpython @stefanfoulis any of you have an idea what might be wrong, can't determine the source of the error.

**Comment by yakky** [comment]
@pratyushsharma Use latest sekizai. IIRC 0.8.2 does not support django 1.9

**Comment by czpython** [comment]
@pratyushsharma Closing for now. Feel free to reopen if latest sekizai does not fix the issue.
