### ISSUE TITLE
UnicodeDecodeError after running installer

### ISSUE THREAD

**Issue by m-aciek** [divio/django-cms#5184]
Hello, I've got an error when running `djangocms -p . my_demo`:
```
Traceback (most recent call last):
  File "/…/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/…/lib/python2.7/site-packages/djangocms_installer/main.py", line 15, in execute
    config_data = config.parse(sys.argv[1:])
  File "/…/lib/python2.7/site-packages/djangocms_installer/config/__init__.py", line 144, in parse
    [path for path in os.listdir(args.project_directory) if not path.startswith('.')]):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 3: ordinal not in range(128)
```
Regards,
Maciej

**Comment by yakky** [comment]
Could you please open this on https://github.com/nephila/djangocms-installer and provide the full set of options you provided to the installer?

**Comment by m-aciek** [comment]
Sure, [there](https://github.com/nephila/djangocms-installer/issues/250) it is.
