### ISSUE TITLE
Upgrading Django 1.9.5 from DjangoCMS 3.2.3 to 3.2.4 causes South issue with migration

### ISSUE THREAD

**Issue by JoeJasinski** [divio/django-cms#5221]
I just upgraded a working copy of DjangoCMS 3.2.3 to DjangoCMS 3.2.4. It looks like the migration "0009_added_meta_fields.py" has references to south, which no longer exists. This causes migrate to break. Migrate works with DjangoCMS 3.2.3.

```
>>> import south
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named south
>>> import django
>>> django.VERSION
(1, 9, 5, 'final', 0)
>>> import cms
>>> cms.__version__
'3.2.4'
```

/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/cms/migrations/0009_added_meta_fields.py

```
# -*- coding: utf-8 -*-
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models
```

Here is the actual error:

```
./manage.py migrate --list
..

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    verbosity=self.verbosity,
  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/core/management/commands/showmigrations.py", line 36, in handle
    return self.show_list(connection, options['app_labels'])
  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/core/management/commands/showmigrations.py", line 44, in show_list
    loader = MigrationLoader(connection, ignore_no_migrations=True)
  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/db/migrations/loader.py", line 170, in build_graph
    self.load_disk()
  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/django/db/migrations/loader.py", line 105, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/jjasinski/Sites/joejasinski/envs/joejasinski/lib/python2.7/site-packages/cms/migrations/0009_added_meta_fields.py", line 3, in <module>
    from south.db import db
ImportError: No module named south.db

```

**Comment by FinalAngel** [comment]
Duplicate from https://github.com/divio/django-cms/issues/5220
