### ISSUE TITLE
IntegrityError when deleting plugin, Key is not present in table "cms_cmsplugin".

### ISSUE THREAD

**Issue by agconti** [divio/django-cms#5261]
When I delete a plugin in my project, django throws an `IntegrityError` because the `CMSPlugin` relation cannot be found or has already been deleted. 

Following this old issue, https://github.com/divio/django-cms/issues/2197, I'm unable to delete the plugin from the command line, by either deleting the plugin instance or the CMSPlugin instance first because the same error is thrown.  

I'm using `django-cms==3.2.5` and `Django==1.9.6`.

Any idea on how to remedy the issue?

Plugin Model:
```python 
from cms.models import Page


@python_2_unicode_compatible
class OfferingPlugin(CMSPlugin):
    image = VersatileImageField(upload_to=unique_upload, ppoi_field='ppoi')
    ppoi = PPOIField()
    title = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=140)
    link_copy = models.CharField(max_length=20)
    link_address = models.ForeignKey(Page, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return "Offering Plugin: {}, {}".format(self.title, self.image)
```
Stack Trace:
```bash
Internal Server Error: /admin/offering/offeringplugin/
Traceback (most recent call last):
  File "/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "/Users/conti/dev/my-app/env/lib/python2.7/site-packages/reversion/admin.py", line 238, in changelist_view
    return super(VersionAdmin, self).changelist_view(request, context)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/Users/conti/dev/my-app/env/lib/python2.7/site-packages/reversion/admin.py", line 89, in _create_revision
    yield
  File "/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/transaction.py", line 223, in __exit__
    connection.commit()
  File "/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/backends/base/base.py", line 242, in commit
    self._commit()
  File "/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/backends/base/base.py", line 211, in _commit
    return self.connection.commit()
  File "/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/backends/base/base.py", line 211, in _commit
    return self.connection.commit()
IntegrityError: insert or update on table "offering_offeringplugin" violates foreign key constraint "offering_offering_cmsplugin_ptr_id_9a9e9998_fk_cms_cmsplugin_id"
DETAIL:  Key (cmsplugin_ptr_id)=(1) is not present in table "cms_cmsplugin".
```

**Comment by czpython** [comment]
@agconti 
Thanks for reporting.
Do you mind removing ``reversion`` from your ``INSTALLED_APPS``? Just for the sake of testing.
Then try and reproduce the issue.

**Comment by agconti** [comment]
@czpython thank you for taking a look.

I removed `reversion` from my installed apps and reproduced the issue. I also cleared my local db, migrated and reproduced the issue again.

**Comment by czpython** [comment]
@agconti This is quite strange. I'll try to reproduce tomorrow.

In the meantime, some questions :)

Which database are you using?
What are the exact steps you're doing to reproduce the problem?

**Comment by agconti** [comment]
@czpython I'm using Postgresql `v9.5.2`.

Here's the steps to reproduce the error form deleteing both the CMSPlugin and the OfferingPlugin:

Setup:
```python
from cms.models import CMSPlugin
from offering.models import OfferingPlugin

offering_plugin = OfferingPlugin.objects.all()[0]
offering_plugin_cms_id = offering_plugin.cmsplugin_ptr_id
# >>> offering_plugin.cmsplugin_ptr_id
# =>  1

related_cms_plugin = CMSPlugin.objects.get(pk=offering_plugin_cms_id)
# >>> CMSPlugin.objects.get(pk=offering_plugin_cms_id)
# <CMSPlugin: 1>
```

CMSPlugin Delete:
```bash
In [16]: related_cms_plugin.delete()

---------------------------------------------------------------------------
IntegrityError                            Traceback (most recent call last)
<ipython-input-16-1f8ee41efd4e> in <module>()
----> 1 related_cms_plugin.delete()

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/cms/models/pluginmodel.pyc in delete(self, no_mp, *args, **kwargs)
    481             Model.delete(self, *args, **kwargs)
    482         else:
--> 483             super(CMSPlugin, self).delete(*args, **kwargs)
    484
    485     def get_action_urls(self, js_compat=True):

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/treebeard/models.pyc in delete(self)
    504     def delete(self):
    505         """Removes a node and all it's descendants."""
--> 506         self.__class__.objects.filter(pk=self.pk).delete()
    507
    508     def _prepare_pos_var(self, pos, method_name, valid_pos, valid_sorted_pos):

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/treebeard/mp_tree.pyc in delete(self)
     96         if toremove:
     97             qset = get_result_class(self.model).objects.filter(reduce(operator.or_, toremove))
---> 98             super(MP_NodeQuerySet, qset).delete()
     99
    100

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/models/query.pyc in delete(self)
    598         collector = Collector(using=del_query.db)
    599         collector.collect(del_query)
--> 600         deleted, _rows_count = collector.delete()
    601
    602         # Clear the result cache, in case this QuerySet gets reused.

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/models/deletion.pyc in delete(self)
    314                     for obj in instances:
    315                         signals.post_delete.send(
--> 316                             sender=model, instance=obj, using=self.using
    317                         )
    318

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/transaction.pyc in __exit__(self, exc_type, exc_value, traceback)
    221                     # Commit transaction
    222                     try:
--> 223                         connection.commit()
    224                     except DatabaseError:
    225                         try:

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/backends/base/base.pyc in commit(self)
    240         self.validate_thread_sharing()
    241         self.validate_no_atomic_block()
--> 242         self._commit()
    243         # A successful commit means that the database connection works.
    244         self.errors_occurred = False

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/backends/base/base.pyc in _commit(self)
    209         if self.connection is not None:
    210             with self.wrap_database_errors:
--> 211                 return self.connection.commit()
    212
    213     def _rollback(self):

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/utils.pyc in __exit__(self, exc_type, exc_value, traceback)
     93                 if dj_exc_type not in (DataError, IntegrityError):
     94                     self.wrapper.errors_occurred = True
---> 95                 six.reraise(dj_exc_type, dj_exc_value, traceback)
     96
     97     def __call__(self, func):

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/backends/base/base.pyc in _commit(self)
    209         if self.connection is not None:
    210             with self.wrap_database_errors:
--> 211                 return self.connection.commit()
    212
    213     def _rollback(self):

IntegrityError: insert or update on table "offering_offeringplugin" violates foreign key constraint "offering_offering_cmsplugin_ptr_id_9a9e9998_fk_cms_cmsplugin_id"
DETAIL:  Key (cmsplugin_ptr_id)=(1) is not present in table "cms_cmsplugin".
```


OfferingPlugin Delete:
```
In [15]: offering_plugin.delete()

---------------------------------------------------------------------------
IntegrityError                            Traceback (most recent call last)
<ipython-input-15-e4f2a078053a> in <module>()
----> 1 offering_plugin.delete()

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/cms/models/pluginmodel.pyc in delete(self, no_mp, *args, **kwargs)
    481             Model.delete(self, *args, **kwargs)
    482         else:
--> 483             super(CMSPlugin, self).delete(*args, **kwargs)
    484
    485     def get_action_urls(self, js_compat=True):

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/treebeard/models.pyc in delete(self)
    504     def delete(self):
    505         """Removes a node and all it's descendants."""
--> 506         self.__class__.objects.filter(pk=self.pk).delete()
    507
    508     def _prepare_pos_var(self, pos, method_name, valid_pos, valid_sorted_pos):

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/treebeard/mp_tree.pyc in delete(self)
     96         if toremove:
     97             qset = get_result_class(self.model).objects.filter(reduce(operator.or_, toremove))
---> 98             super(MP_NodeQuerySet, qset).delete()
     99
    100

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/models/query.pyc in delete(self)
    598         collector = Collector(using=del_query.db)
    599         collector.collect(del_query)
--> 600         deleted, _rows_count = collector.delete()
    601
    602         # Clear the result cache, in case this QuerySet gets reused.

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/models/deletion.pyc in delete(self)
    314                     for obj in instances:
    315                         signals.post_delete.send(
--> 316                             sender=model, instance=obj, using=self.using
    317                         )
    318

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/transaction.pyc in __exit__(self, exc_type, exc_value, traceback)
    221                     # Commit transaction
    222                     try:
--> 223                         connection.commit()
    224                     except DatabaseError:
    225                         try:

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/backends/base/base.pyc in commit(self)
    240         self.validate_thread_sharing()
    241         self.validate_no_atomic_block()
--> 242         self._commit()
    243         # A successful commit means that the database connection works.
    244         self.errors_occurred = False

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/backends/base/base.pyc in _commit(self)
    209         if self.connection is not None:
    210             with self.wrap_database_errors:
--> 211                 return self.connection.commit()
    212
    213     def _rollback(self):

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/utils.pyc in __exit__(self, exc_type, exc_value, traceback)
     93                 if dj_exc_type not in (DataError, IntegrityError):
     94                     self.wrapper.errors_occurred = True
---> 95                 six.reraise(dj_exc_type, dj_exc_value, traceback)
     96
     97     def __call__(self, func):

/Users/conti/dev/my-app/env/lib/python2.7/site-packages/django/db/backends/base/base.pyc in _commit(self)
    209         if self.connection is not None:
    210             with self.wrap_database_errors:
--> 211                 return self.connection.commit()
    212
    213     def _rollback(self):

IntegrityError: insert or update on table "offering_offeringplugin" violates foreign key constraint "offering_offering_cmsplugin_ptr_id_9a9e9998_fk_cms_cmsplugin_id"
DETAIL:  Key (cmsplugin_ptr_id)=(1) is not present in table "cms_cmsplugin".
```

**Comment by agconti** [comment]
Also @czpython, its worth mentioning that I'm having this issue with several plugins. I've only included the `OfferingPlugin` here so that we could zero in a single representative problem.

**Comment by agconti** [comment]
@czpython, I found that I needed to remove admin.py's that us a reversion admin in addition to removing `reversion` from my INSTALLED_APPS. 

Once they're all removed, the problem no longer occurs. Do you have any insight on why this might be happening with Django-cms?

**Comment by czpython** [comment]
@agconti are you using aldryn-reversion anywhere? (most aldryn addons use it).

**Comment by agconti** [comment]
I was using` django-reversion==1.10.1`.  Should I be using ` aldryn-reversion` instead?

**Comment by czpython** [comment]
@agconti Aldryn reversion is an extension of django-reversion to encapsulate cms specific reversion logic for cms apps. The reason I mention it is because if you do have it in your installed apps but not reversion then it still uses it. But seems like this is not the case.

I'm very intrigued though as to how it was still failing with the reversion out of installed apps.

Just to be sure, are you positive that the error stopped **only** when removing the admin.py?

**Comment by agconti** [comment]
@czpython yes. 

That's why I originally reported that `django-reversion` must not be related; because I removed it from my installed apps when I tested. Later, Just to exhaust all testing possibilities and because you mentioned that `django-reversion` might be the issue,  I removed it and the admin.pys and tried again.

**Comment by mateuspadua** [comment]
I did many tests and I figure out that the problem is when have null=True inside ForeignKey. Django don't to do CASCADE Operation even passing on_delete=models.CASCADE.

link_address = models.ForeignKey(Page, blank=True, **null=True**, on_delete=models.CASCADE) **-> dont work CASCADE**

link_address = models.ForeignKey(Page, on_delete=models.CASCADE) **-> will work CASCADE**

I believe this is bug in Django.

**Comment by mateuspadua** [comment]
UPDATE: I did more tests and i figure out that my constraint was without the options **Deferrable** and **Deferred** assigned, because my current DB PostgreSQL was migrate from MySQL.
More information about this options on the link bellow:
http://stackoverflow.com/questions/16323236/deferrable-check-constraint-in-postgresql

I hope this can help.
