### ISSUE TITLE
manage.py cms check crashes

### ISSUE THREAD

**Issue by bxm156** [divio/django-cms#5456]
Not sure whats going on, but  when I tried to run cms check, i got...

```
Plugin instances
================

Checker failed, see traceback [ERROR]
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/cms/management/commands/subcommands/base.py", line 24, in handle
    handle_command.handle(*args[1:], **options)
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/django/core/management/base.py", line 584, in handle
    return self.handle_noargs(**options)
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/cms/management/commands/subcommands/check.py", line 10, in handle_noargs
    if not check(FileOutputWrapper(self.stdout, self.stderr)):
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/cms/utils/check.py", line 403, in check
    checker(output)
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/cms/utils/check.py", line 259, in check_plugin_instances
    report = plugin_report()
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/cms/management/commands/subcommands/list.py", line 64, in plugin_report
    unsaved_instances = [p for p in plugins if not p.get_plugin_instance()[0]]
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/cms/models/pluginmodel.py", line 156, in get_plugin_instance
    instance = plugin.model.objects.get(cmsplugin_ptr=self)
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/django/db/models/query.py", line 68, in __iter__
    for row in compiler.results_iter(results):
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 808, in results_iter
    row = self.apply_converters(row, converters)
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 792, in apply_converters
    value = converter(value, expression, self.connection, self.query.context)
  File "/home/queercon/.env/queercon/local/lib/python2.7/site-packages/jsonfield/fields.py", line 84, in from_db_value
    return json.loads(value, **self.decoder_kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

```

Django==1.9.6
django-cms==3.2.5

**Comment by czpython** [comment]
@bxm156 
Hi there,
Do you have djangocms-link installed? If so can you comment it out in `INSTALLED_APPS` and run the command again?

**Comment by yakky** [comment]
@czpython @bxm156 see https://github.com/divio/djangocms-attributes-field/issues/7

**Comment by czpython** [comment]
Closing in favor of https://github.com/divio/djangocms-attributes-field/issues/7
