### ISSUE TITLE
UnicodeDecodeError when using publisher-publish.

### ISSUE THREAD

**Issue by philippeowagner** [divio/django-cms#5490]
Publishing using `python manage.py cms publisher-publish` raises an unicode decode error using cms==3.3.0 and Django==1.8.x.

    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/.../www/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
        utility.execute()
      File "/.../www/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/.../www/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/.../www/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
        output = self.handle(*args, **options)
      File "/.../www/lib/python2.7/site-packages/cms/management/commands/subcommands/base.py", line 86, in handle
        command.handle(*args, **options)
      File "/.../www/lib/python2.7/site-packages/cms/management/commands/subcommands/publisher_publish.py", line 47, in handle
        self.stdout.write('%d.\t%s  %s [%d]\n' % (index + 1, m, force_text(page), page.id))
      File "/.../www/lib/python2.7/site-packages/django/core/management/base.py", line 114, in write
        self._out.write(force_str(style_func(msg)))
      File "/.../www/lib/python2.7/site-packages/django/core/management/base.py", line 111, in write
        if ending and not msg.endswith(ending):
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)

**Comment by czpython** [comment]
Hello @philippeowagner,
I believe your system python's encoding is not utf8, try running the command like so:

`PYTHONIOENCODING=utf8 python manage.py cms publisher-publish`

**Comment by philippeowagner** [comment]
Thanks @czpython for your reply. The issue persists.

**Comment by czpython** [comment]
@philippeowagner 
I can reproduce the issue. Got a patching in the works.
