### ISSUE TITLE
MIgration 0016_auto_20160608_1535 of 3.3.1 results in IndexError: list index out of range

### ISSUE THREAD

**Issue by jgoettsch** [divio/django-cms#5538]
Django 1.8.13, Django-CMS 3.3.1, PostgreSQL.

This is the output:

```
$ python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: mptt, staticfiles, messages, djangocms_admin_style, compressor, sekizai, treebeard
  Apply all migrations: cmsplugin_filer_image, agribusiness, menus, reversion, filer, admin, agribusiness_people, sessions, contenttypes, auth, sites, agribusiness_extensions, cmsplugin_filer_link, cms, easy_thumbnails, djangocms_text_ckeditor
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying cms.0016_auto_20160608_1535...Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/envs/foo.example.com/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/envs/foo.example.com/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/envs/foo.example.com/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/envs/foo.example.com/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/envs/foo.example.com/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/envs/foo.example.com/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/envs/foo.example.com/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/envs/foo.example.com/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/envs/foo.example.com/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 201, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/envs/foo.example.com/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 484, in alter_field
    old_db_params, new_db_params, strict)
  File "/usr/local/envs/foo.example.com/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/schema.py", line 107, in _alter_field
    new_db_params, strict,
  File "/usr/local/envs/foo.example.com/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 493, in _alter_field
    fk_names = self._constraint_names(model, [old_field.column], foreign_key=True)
  File "/usr/local/envs/foo.example.com/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 913, in _constraint_names
    constraints = self.connection.introspection.get_constraints(cursor, model._meta.db_table)
  File "/usr/local/envs/foo.example.com/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/introspection.py", line 169, in get_constraints
    "foreign_key": tuple(used_cols[0].split(".", 1)) if kind.lower() == "foreign key" else None,
IndexError: list index out of range
```

This is what I have installed:

```
$ pip freeze
click==6.6
cmsplugin-filer==1.1.2
Django==1.8.13
django-appconf==1.0.2
django-auth-ldap==1.2.8
django-classy-tags==0.7.2
django-cms==3.3.1
django-compressor==2.0
django-filer==1.2.4
django-formtools==1.0
django-mptt==0.8.4
django-polymorphic==0.8.1
django-reversion==1.10.2
django-sekizai==0.9.0
django-treebeard==4.0.1
djangocms-admin-style==1.2.3
djangocms-attributes-field==0.1.1
djangocms-text-ckeditor==3.0.0
easy-thumbnails==2.3
first==2.0.1
html5lib==0.9999999
Pillow==3.3.0
pip-tools==1.7.0
psycopg2==2.6.2
python-ldap==2.4.25
python-memcached==1.58
pytz==2016.6
rcssmin==1.0.6
rjsmin==1.0.12
six==1.10.0
Unidecode==0.4.19
virtualenv==13.1.0
```

**Comment by czpython** [comment]
@jgoettsch 
Hi there,

This one is quite strange.
Are you upgrading an existing project? or fresh install?
Also what PostgreSQL version are you running?

**Comment by jgoettsch** [comment]
Fresh install of 3.3 yesterday went fine. Tried to update to 3.3.1 today. The migration was fine on my dev box, but failed on my staging server. Both are running identical software, the database contents are identical.

PostgreSQL is 9.2 from the CentOS 6 Software Collections Library.

**Comment by czpython** [comment]
@jgoettsch 
This looks like an issue with your postgres install on the staging server.
Have a look at https://code.djangoproject.com/ticket/25476

**Comment by jgoettsch** [comment]
That looks to be the case.

Thanks for the quick help and sorry for the extra noise.
