### ISSUE TITLE
Version 3.3.1 introduces error Cannot query "ContentType object": Must be "ContentType" instance

### ISSUE THREAD

**Issue by Flimm** [divio/django-cms#5589]
I am following the instructions to how to [install Django CMS by hand](http://docs.django-cms.org/en/stable/how_to/install.html).

When I try to run `python manage.py migrate` or `python manage.py test`, I get this error:

    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 330, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
        super(Command, self).run_from_argv(argv)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/base.py", line 390, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/commands/test.py", line 74, in execute
        super(Command, self).execute(*args, **options)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/base.py", line 441, in execute
        output = self.handle(*args, **options)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/commands/test.py", line 90, in handle
        failures = test_runner.run_tests(test_labels)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/test/runner.py", line 210, in run_tests
        old_config = self.setup_databases()
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/test/runner.py", line 166, in setup_databases
        **kwargs
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/test/runner.py", line 370, in setup_databases
        serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 368, in create_test_db
        test_flush=True,
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 120, in call_command
        return command.execute(*args, **defaults)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/base.py", line 441, in execute
        output = self.handle(*args, **options)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 221, in handle
        executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/migrations/executor.py", line 110, in migrate
        self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
        state = migration.apply(state, schema_editor)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/migrations/migration.py", line 112, in apply
        operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 181, in database_forwards
        self.code(from_state.apps, schema_editor)
      File "/flimm/git/example/env/lib/python3.5/site-packages/cms/migrations/0014_auto_20160404_1908.py", line 14, in forwards
        codename='change_page', content_type=page_ctype).update(name='Can change page')
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/models/query.py", line 679, in filter
        return self._filter_or_exclude(False, *args, **kwargs)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/models/query.py", line 697, in _filter_or_exclude
        clone.query.add_q(Q(*args, **kwargs))
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1301, in add_q
        clause, require_inner = self._add_q(where_part, self.used_aliases)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1328, in _add_q
        current_negated=current_negated, connector=connector, allow_joins=allow_joins)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1170, in build_filter
        self.check_related_objects(field, value, opts)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1068, in check_related_objects
        self.check_query_object_type(value, opts)
      File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1052, in check_query_object_type
        (value, opts.object_name))
    ValueError: Cannot query "ContentType object": Must be "ContentType" instance.

I do not get this error if I use Django CMS version 3.3.0, or 3.3.0rc4, or 3.3.0rc3, or 3.3.0rc2 instead. I am using Python 3.5 and Django 1.8.

**Comment by czpython** [comment]
Thanks! Fixed by eca00bac1e5af4ecf5b4322f5f4a1bbf4b8db964

**Comment by Flimm** [comment]
Brilliant! Thanks so much @czpython .

**Comment by Flimm** [comment]
Hmm, I don't think this has fixed it. I tried upgrading to the last commit on master, and I got this error upon running `python manage.py migrate`:

```
...
  Applying reversion.0001_initial... OK
  Applying reversion.0002_auto_20141216_1509... OK
  Applying sessions.0001_initial... OK
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 225, in handle
    emit_post_migrate_signal(created_models, self.verbosity, self.interactive, connection.alias)
  File "/flimm/git/example/env/lib/python3.5/site-packages/django/core/management/sql.py", line 280, in emit_post_migrate_signal
    using=db)
  File "/flimm/git/example/env/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/flimm/git/example/env/lib/python3.5/site-packages/django/contrib/auth/management/__init__.py", line 91, in create_permissions
    content_type__in=ctypes,
  File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/models/query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/models/query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1301, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1328, in _add_q
    current_negated=current_negated, connector=connector, allow_joins=allow_joins)
  File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1170, in build_filter
    self.check_related_objects(field, value, opts)
  File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1071, in check_related_objects
    self.check_query_object_type(v, opts)
  File "/flimm/git/example/env/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1052, in check_query_object_type
    (value, opts.object_name))
ValueError: Cannot query "ContentType object": Must be "ContentType" instance.
```

**Comment by czpython** [comment]
Hello @Flimm ,
Based on the traceback, the cms is no longer triggering this error.
Instead it's coming from a call to the `create_permissions` command.
I think https://code.djangoproject.com/ticket/23422 is related.

Try removing revisions from installed apps just for the sake of testing.

**Comment by Flimm** [comment]
I'll see if I can spend some time looking at that.

In any case, this error only happens with the newer version of django-cms. So even if the bug is elsewhere, only the newer version of django-cms is triggering it.

**Comment by czpython** [comment]
@Flimm If you don't have django-cms in your installed apps, the error no longer shows?
If so can you provide us with a pip freeze and your settings? Thanks

**Comment by Flimm** [comment]
Yes, removing `'cms'` from installed apps fixes the issue. Staying on Django CMS 3.3.0 instead of 3.3.1 works.

Here's the [output of pip freeze when it's broken](https://github.com/divio/django-cms/files/434980/frozen_broken.txt) and when Django CMS is set to 3.3.1. And here's the [output of pip freeze when it's not broken](https://github.com/divio/django-cms/files/434956/frozen.txt) and when Django CMS is set to 3.3.0.

Here is the [`settings.py` file](https://github.com/divio/django-cms/files/434988/settings.py.txt).

**Comment by Flimm** [comment]
Django CMS 3.4.1 seems to fix this issue.
