### ISSUE TITLE
manage.py cms fix-tree is broken (IntegrityError: duplicate key value violates unique constraint)

### ISSUE THREAD

**Issue by vstoykov** [divio/django-cms#5690]
These days when I executed `manage.py cms fix-tree` I received the following error.

    fixing page tree
    Traceback (most recent call last):
    File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
    psycopg2.IntegrityError: duplicate key value violates unique constraint "cms_page_path_72b7799ffb81eabf_uniq"
    DETAIL:  Key (path)=(00030001) already exists.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
    File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
    File "/path/to/virtualenv/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
        utility.execute()
    File "/path/to/virtualenv/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
    File "/path/to/virtualenv/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
        self.execute(*args, **cmd_options)
    File "/path/to/virtualenv/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
        output = self.handle(*args, **options)
    File "/path/to/virtualenv/lib/python3.4/site-packages/cms/management/commands/subcommands/base.py", line 84, in handle
        command.handle(*args, **options)
    File "/path/to/virtualenv/lib/python3.4/site-packages/cms/management/commands/subcommands/tree.py", line 32, in handle
        page.move(target=last, pos='right')
    File "/path/to/virtualenv/lib/python3.4/site-packages/cms/models/pagemodel.py", line 1420, in move
        super(Page, self).move(target, pos)
    File "/path/to/virtualenv/lib/python3.4/site-packages/treebeard/mp_tree.py", line 1037, in move
        return MP_MoveHandler(self, target, pos).process()
    File "/path/to/virtualenv/lib/python3.4/site-packages/treebeard/mp_tree.py", line 481, in process
        self.run_sql_stmts()
    File "/path/to/virtualenv/lib/python3.4/site-packages/treebeard/mp_tree.py", line 119, in run_sql_stmts
        cursor.execute(sql, vals)
    File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
        return super(CursorDebugWrapper, self).execute(sql, params)
    File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
    File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/utils.py", line 98, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
    File "/path/to/virtualenv/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
        raise value.with_traceback(tb)
    File "/path/to/virtualenv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
    django.db.utils.IntegrityError: duplicate key value violates unique constraint "cms_page_path_72b7799ffb81eabf_uniq"
    DETAIL:  Key (path)=(00030001) already exists.

I'm using

 - Python 3.4;
 - Django 1.8;
 - Django CMS 3.3
 - Django Treebeard 4.0

P.P. Reversion is enabled

**Comment by czpython** [comment]
Hello @vstoykov,
This is not a bug in fix-tree, instead it's an unfortunate side-effect of the publisher corruption.
Please use your [script](https://github.com/divio/django-cms/issues/5667#issuecomment-245284499) to fix the publisher corruptions and then run fix-tree. If you are using revision in this project, I highly recommend to drop it for cms pages as it has a lot of issues like this.

**Comment by vstoykov** [comment]
I think that this is not a publisher corruption but instead treebeard coruption because the duplicate key is in the `path` field which is from `django-treebeard`.

Also my script can't solve this problem (I executed it before `cms fix-tree`) because it only touches `publisher_public_id` and not tree related stuff.

Yes probably the main reason is reversion integration but still this is different issue than publisher corruption.

**Comment by czpython** [comment]
Did you try checking for the publisher corruption?
I understand that the duplicate key is in the path field but in all my tests this is caused by the publisher corruption which causes the cms to incorrectly move the pages. You can confirm this yourself if you comment out [this](https://github.com/divio/django-cms/blob/release/3.4.x/cms/management/commands/subcommands/tree.py#L18) line which is the only one actually recalculating paths using treebeard, and then run the command again it should still error out. The rest of the code will move pages around and here is where it fails because pages are moved according to their publisher attributes which are corrupt.

**Comment by vstoykov** [comment]
I saw that it try to move the page. It is very strange that moving the page actually can't be done because of the `path` duplication. This process need to be independent from the publisher. Probably there is also bug in django-treebeard or something really strange is happening here.
