### ISSUE TITLE
install error django-cms 3.4.1 on windows 10 64bit

### ISSUE THREAD

**Issue by jankrnavek** [divio/django-cms#5726]
Hello,
im not able to install  django-cms 3.4.1 on windows 10 64bit in latest Pycharms env..
(python 3.5 64bit, virtualenv enable)

I attach error log bellow.
Thank you for fix in advance,
Hanz

Collecting django-cms==3.4.1
  Using cached django_cms-3.4.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): djangocms-admin-style>=1.0 in c:\users\hanz\env-cms\lib\site-packages (from django-cms==3.4.1)
Requirement already satisfied (use --upgrade to upgrade): django-sekizai>=0.7 in c:\users\hanz\env-cms\lib\site-packages (from django-cms==3.4.1)
Requirement already satisfied (use --upgrade to upgrade): django-classy-tags>=0.7.2 in c:\users\hanz\env-cms\lib\site-packages (from django-cms==3.4.1)
Requirement already satisfied (use --upgrade to upgrade): Django<1.10,>=1.8 in c:\users\hanz\env-cms\lib\site-packages (from django-cms==3.4.1)
Requirement already satisfied (use --upgrade to upgrade): django-formtools>=1.0 in c:\users\hanz\env-cms\lib\site-packages (from django-cms==3.4.1)
Requirement already satisfied (use --upgrade to upgrade): django-treebeard>=4.0.1 in c:\users\hanz\env-cms\lib\site-packages (from django-cms==3.4.1)
Installing collected packages: django-cms
  Found existing installation: django-cms 3.4.0
    Uninstalling django-cms-3.4.0:

Exception:
Traceback (most recent call last):
  File "C:\Python35\lib\shutil.py", line 538, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\users\\hanz\\env-cms\\lib\\site-packages\\cms\\test_utils\\project\\extensionapp\\migrations\\__pycache__\\0003_multitablepageextension_multitablepageextensionparent_multitabletitleextension_multitabletitleextens.cpython-35.pyc' -> 'C:\\Users\\hanz\\AppData\\Local\\Temp\\pip-w6v14wb7-uninstall\\users\\hanz\\env-cms\\lib\\site-packages\\cms\\test_utils\\project\\extensionapp\\migrations\\__pycache__\\0003_multitablepageextension_multitablepageextensionparent_multitabletitleextension_multitabletitleextens.cpython-35.pyc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hanz\env-cms\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\hanz\env-cms\lib\site-packages\pip\commands\install.py", line 317, in run
    prefix=options.prefix_path,
  File "C:\Users\hanz\env-cms\lib\site-packages\pip\req\req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "C:\Users\hanz\env-cms\lib\site-packages\pip\req\req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "C:\Users\hanz\env-cms\lib\site-packages\pip\req\req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "C:\Users\hanz\env-cms\lib\site-packages\pip\utils\__init__.py", line 267, in renames
    shutil.move(old, new)
  File "C:\Python35\lib\shutil.py", line 552, in move
    copy_function(src, real_dst)
  File "C:\Python35\lib\shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python35\lib\shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\hanz\\AppData\\Local\\Temp\\pip-w6v14wb7-uninstall\\users\\hanz\\env-cms\\lib\\site-packages\\cms\\test_utils\\project\\extensionapp\\migrations\\__pycache__\\0003_multitablepageextension_multitablepageextensionparent_multitabletitleextension_multitabletitleextens.cpython-35.pyc'

**Comment by czpython** [comment]
Hello @jankrnavek,
Does this only happen with 3.4.1?

**Comment by jankrnavek** [comment]
Hello,
i found, where is problem.  Version 3.4.1 cannot overwrite  v.3.4.0.   I had to delete 3.4.0 manually.  (remove dir site-packages/django_cms-3.4.1.dist-info)  and install 3.4.1 into clear dir.
Hanz

**Comment by czpython** [comment]
Cool, thanks for the update.

**Comment by naseebbajracharya** [comment]
unable to uninstall django
Exception:
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\basecommand.py", line 141, in main
    status = self.run(options, args)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\commands\uninstall.py", line 74, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\req\req_install.py", line 863, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\req\req_uninstall.py", line 357, in from_dist
    for path in uninstallation_paths(dist):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\req\req_uninstall.py", line 50, in unique
    for item in fn(*args, **kw):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\req\req_uninstall.py", line 67, in uninstallation_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1404, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1400, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1512, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\dell\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\django-1.8.dist-info\\RECORD'
