### ISSUE TITLE
Can't load page tree after adding new language

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#5771]
Django: 1.8.16
django-cms: 3.4.1

I've added Canadian French to the languages after having the system setup, and translating to French;

```python
LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', gettext('English')),
    ('fr', gettext('French')),
    ('fr-CA', gettext('Canadian French')),
]

CMS_LANGUAGES = {
    1: [
        {
            'code': 'en',
            'name': gettext('English'),
            'public': True,
            'hide_untranslated': True,
            'redirect_on_fallback': False
        },
        {
            'code': 'fr',
            'name': gettext('French'),
            'public': True,
            'hide_untranslated': True,
            'redirect_on_fallback': False
        },
        {
            'code': 'fr-CA',
            'name': gettext('Canadian French'),
            'public': True,
            'hide_untranslated': True,
            'redirect_on_fallback': True
        },

    ],
    'default': {
        'fallbacks': ['en'],
        'redirect_on_fallback': True,
        'public': True,
        'hide_untranslated': False,
    }
}
```

However, now I can't load the page tree;

```bash
127.0.0.1 - - [23/Nov/2016 11:13:10] "GET /en/admin/cms/page/get-tree/?language=en&openNodes%5B%5D=1&pageId=&site=1&_=1479899590119 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/cms/admin/pageadmin.py", line 1118, in get_tree
    response = render_admin_rows(request, pages, site=site, filtered=False)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/cms/utils/admin.py", line 131, in render_admin_rows
    return ''.join(rendered)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/cms/utils/admin.py", line 130, in <genexpr>
    rendered = (render_page_row(page) for page in pages)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/cms/utils/admin.py", line 128, in render_page_row
    return template.render(context)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/template/defaulttags.py", line 444, in render
    return strip_spaces_between_tags(self.nodelist.render(context).strip())
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/mwalker/Sites/rnr-us/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'cms_page_preview_page' with arguments '(1L, 'fr-CA')' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'en/admin/cms/page/([0-9]+)/([a-z\\-]+)/preview/$']
```

Any ideas chaps? Am I missing something obvious? I was about to publish some pages in the new language!

**Comment by marksweb** [comment]
Ok, I'm an idiot. I actually read the regex in the URL there. Needs lowercase language codes then...
