### ISSUE TITLE
Reversion is still not removed

### ISSUE THREAD

**Issue by Someguy123** [divio/django-cms#5830]
```
CMS Version: 3.4.1 (from pip)
Reversion Version: 2.0.8
```
Supposedly it was removed from 3.4, but sadly it isn't.

I'm using Reversion 2.0.8 within my project, and it's causing django-cms to refuse to run:

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1095bbe18>
Traceback (most recent call last):
  File "[REDACTED]/env/lib/python3.5/site-packages/cms/utils/reversion_hacks.py", line 7, in <module>
    from reversion.admin import VersionAdmin as ModelAdmin, RollBackRevisionView  # NOQA  # nopyflakes
ImportError: cannot import name 'RollBackRevisionView'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[REDACTED]/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "[REDACTED]/env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "[REDACTED]/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "[REDACTED]/env/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "[REDACTED]/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "[REDACTED]/env/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "[REDACTED]/env/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "[REDACTED]/env/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "[REDACTED]/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "[REDACTED]/env/lib/python3.5/site-packages/cms/models/__init__.py", line 3, in <module>
    from .pagemodel import *  # nopyflakes
  File "[REDACTED]/env/lib/python3.5/site-packages/cms/models/pagemodel.py", line 1453, in <module>
    _reversion()
  File "[REDACTED]/env/lib/python3.5/site-packages/cms/models/pagemodel.py", line 1449, in _reversion
    exclude_fields=exclude_fields
  File "[REDACTED]/env/lib/python3.5/site-packages/cms/utils/helpers.py", line 135, in reversion_register
    from cms.utils import reversion_hacks
  File "[REDACTED]/env/lib/python3.5/site-packages/cms/utils/reversion_hacks.py", line 18, in <module>
    from reversion.models import Revision, Version, post_revision_commit  # NOQA  # nopyflakes
ImportError: cannot import name 'post_revision_commit'
```

I attempted to manually cut out the remainder of revision code from `plugin_pool.py` and  `helpers.py` (L119), however I ended up with the following error (possibly related?):

```
File "REDACTED/env/lib/python3.5/site-packages/cms/admin/__init__.py", line 11, in <module>
    plugin_pool.plugin_pool.discover_plugins()
  File "REDACTED/env/lib/python3.5/site-packages/cms/plugin_pool.py", line 34, in discover_plugins
    load('cms_plugins')
  File "REDACTED/env/lib/python3.5/site-packages/cms/utils/django_load.py", line 57, in load
    get_module(app, modname, verbose, failfast)
  File "REDACTED/env/lib/python3.5/site-packages/cms/utils/django_load.py", line 29, in get_module
    imp.find_module(modname, app_mod.__path__ if hasattr(app_mod, '__path__') else None)
  File "REDCATED/env/lib/python3.5/imp.py", line 270, in find_module
    "not {}".format(type(name)))
RuntimeError: 'list' must be None or a list, not <class 'str'>
```

**Comment by czpython** [comment]
Hello @Someguy123,
Thanks for the report.

We removed the integration to django-reversion but left the registration of cms models to the reversion app on purpose.

The reason being that lots of third party apps rely on these models being registered with the reversion system and would have failed loudly on upgrade.

This shim will be fully removed on 3.5
