### ISSUE TITLE
Apps aren't loaded yet. error

### ISSUE THREAD

**Issue by useHTML5** [divio/django-cms#5862]
### Summary

I add placeholder field to model in other app. Its app a part of django-lfs. When I try to make migration or runserver i have a error:

```
(env)workeuser@simpleuser:~/work/projects/2016/iron/django_project$ python manage.py 0.0.0.0:9000
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/workeuser/work/projects/2016/iron/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/workeuser/work/projects/2016/iron/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/workeuser/work/projects/2016/iron/env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/workeuser/work/projects/2016/iron/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/workeuser/work/projects/2016/iron/env/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/workeuser/work/projects/2016/iron/django_project/lfs/caching/__init__.py", line 1, in <module>
    from listeners import *
  File "/home/workeuser/work/projects/2016/iron/django_project/lfs/caching/listeners.py", line 11, in <module>
    from lfs.cart.models import Cart
  File "/home/workeuser/work/projects/2016/iron/django_project/lfs/cart/models.py", line 13, in <module>
    import lfs.catalog.utils
  File "/home/workeuser/work/projects/2016/iron/django_project/lfs/catalog/__init__.py", line 1, in <module>
    from listeners import *
  File "/home/workeuser/work/projects/2016/iron/django_project/lfs/catalog/listeners.py", line 9, in <module>
    from lfs.catalog.models import File, Property
  File "/home/workeuser/work/projects/2016/iron/django_project/lfs/catalog/models.py", line 92, in <module>
    class Category(models.Model):
  File "/home/workeuser/work/projects/2016/iron/django_project/lfs/catalog/models.py", line 167, in Category
    category_placeholder = ppField('category_placeholder')
  File "/home/workeuser/work/projects/2016/iron/django_project/lfs/catalog/models.py", line 89, in ppField
    from cms.models.fields import PlaceholderField
  File "/home/workeuser/work/projects/2016/iron/env/local/lib/python2.7/site-packages/cms/models/__init__.py", line 3, in <module>
    from .pagemodel import *  # nopyflakes
  File "/home/workeuser/work/projects/2016/iron/env/local/lib/python2.7/site-packages/cms/models/pagemodel.py", line 1512, in <module>
    _reversion()
  File "/home/workeuser/work/projects/2016/iron/env/local/lib/python2.7/site-packages/cms/models/pagemodel.py", line 1508, in _reversion
    exclude_fields=exclude_fields
  File "/home/workeuser/work/projects/2016/iron/env/local/lib/python2.7/site-packages/cms/utils/helpers.py", line 119, in reversion_register
    if not is_installed('reversion'):
  File "/home/workeuser/work/projects/2016/iron/env/local/lib/python2.7/site-packages/cms/utils/compat/dj.py", line 18, in is_installed
    return apps.is_installed(app_name)
  File "/home/workeuser/work/projects/2016/iron/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 231, in is_installed
    self.check_apps_ready()
  File "/home/workeuser/work/projects/2016/iron/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

code in app:

```
from cms.models.fields import PlaceholderField

class Category(models.Model):
    name = models.CharField(_(u"Name"), max_length=50)
    slug = models.SlugField(_(u"Slug"), unique=True)
    parent = models.ForeignKey("self", verbose_name=_(u"Parent"), blank=True, null=True)

    category_placeholder = PlaceholderField('category_placeholder')
```

I remove check 

```
 if not is_installed('reversion'):
     return
```
in 

/cms/utils/helpers.py

and all works, but i think its a not good way.

#### Environment

* Python version:
* Django version: 1.8.9
* django CMS version: 3.4.2

**Comment by timgraham** [comment]
This is a problem in your application, not django-cms. `lfs/catalog/__init__.py` shouldn't import models. https://docs.djangoproject.com/en/stable/ref/applications/#troubleshooting

**Comment by czpython** [comment]
Thanks @timgraham.
Closing as this is not a django CMS issue.
