### ISSUE TITLE
onPluginSave does not reload if site inside iframe: Uncaught DOMException: Blocked a frame with origin

### ISSUE THREAD

**Issue by marguslaak** [divio/django-cms#5881]
### Summary
When you embed the whole site into an iframe and try to save panels, then almost everything works, except reloading the page inside iframe after a successful save.

### Expected behaviour
Page inside iframe will be reloaded after a successful plugin save.

#### Actual behaviour
There is an access isssue:
Uncaught DOMException: Blocked a frame with origin "http://******.org" from accessing a cross-origin frame.
    at Object.reloadBrowser (http://******.org/static/cms/js/dist/3.4.2/bundle.toolbar.min.js:4:1411)
    at HTMLIFrameElement.<anonymous> (http://******.org/static/cms/js/dist/3.4.2/bundle.toolbar.min.js:4:20104)
    at HTMLIFrameElement.dispatch (http://******.org/static/cms/js/dist/3.4.2/bundle.toolbar.min.js:2:18217)
    at HTMLIFrameElement.g.handle (http://******.org/static/cms/js/dist/3.4.2/bundle.toolbar.min.js:2:14889)

#### Quickfix that worked for me

However, if overrided cms/page/close_frame.html and used window.parent.location.reload() then it works ok.

#### Environment

* Python version:  3.5.2
* Django version: 1.8.17
* django CMS version: 3.4.2

**Comment by czpython** [comment]
Hello @marguslaak,
Thanks for reporting.

We don't support embedding the site while on edit-mode in an iframe.
Closing as a won't fix.
