### ISSUE TITLE
AttributeError: 'WSGIRequest' object has no attribute 'is_superuser'

### ISSUE THREAD

**Issue by plus500s** [divio/django-cms#5931]
### Summary
Seems like there is a request object passed instead of user at some point. See traceback below:

```
Traceback (most recent call last):
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.6/site-packages/django/views/decorators/clickjacking.py", line 39, in wrapped_view
    resp = view_func(*args, **kwargs)
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.6/site-packages/djangocms_text_ckeditor/cms_plugins.py", line 221, in render_plugin
    text_plugin.placeholder.has_change_permission(request)):
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.6/site-packages/cms/models/placeholdermodel.py", line 123, in has_change_permission
    if user.is_superuser:
AttributeError: 'WSGIRequest' object has no attribute 'is_superuser'
```

### Expected behaviour
I was trying to add a plugin via Text plugin (wysiwyg) and expected to add a link to another django cms page.

#### Actual behaviour
Nothing happened in UI but error raised in console (suppose in ajax call).

#### Environment

* Python version: 3.6.1
* Django version: 1.10
* django CMS version: 3.4.3

**Comment by czpython** [comment]
Hello @plus500s,
This is an issue with the text editor app (djangocms-text-ckeditor).
Please have a look at the (README](https://github.com/divio/djangocms-text-ckeditor#djangocms-text-ckeditor) to make sure you're using the right version of the app for your cms verisoin

**Comment by Gnouc** [comment]
@czpython I used Django CMS 3.3.1 and Django CMS text ckeditor 3.1.0 but still get this error
