### ISSUE TITLE
Cannot install basic project

### ISSUE THREAD

**Issue by pavelschon** [divio/django-cms#6134]
### Summary
Cannot install basic project (following _Howto_ from the homepage)

### Actual behaviour
```
$ pwd
/tmp
$ mkdir MySite
$ cd MySite
$ virtualenv env
Using base prefix '/usr'
New python executable in /tmp/MySite/env/bin/python3
Also creating executable in /tmp/MySite/env/bin/python
Installing setuptools, pip, wheel...done.
$ source env/bin/activate
(env) $ pip install djangocms-installer
Collecting djangocms-installer
  Using cached djangocms_installer-0.9.7-py2.py3-none-any.whl
Collecting argparse (from djangocms-installer)
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Collecting six (from djangocms-installer)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting tzlocal (from djangocms-installer)
Collecting dj-database-url>=0.4 (from djangocms-installer)
  Using cached dj_database_url-0.4.2-py2.py3-none-any.whl
Requirement already satisfied: pip in ./env/lib/python3.4/site-packages (from djangocms-installer)
Collecting pytz (from tzlocal->djangocms-installer)
  Using cached pytz-2017.3-py2.py3-none-any.whl
Installing collected packages: argparse, six, pytz, tzlocal, dj-database-url, djangocms-installer
Successfully installed argparse-1.4.0 dj-database-url-0.4.2 djangocms-installer-0.9.7 pytz-2017.3 six-1.11.0 tzlocal-1.4
(env) $ djangocms mysite
Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the project
CommandError: 'mysite' conflicts with the name of an existing Python module and cannot be used as a project name. Please try another name.
The installation has failed.


*****************************************************************

Check documentation at https://djangocms-installer.readthedocs.io

*****************************************************************

Traceback (most recent call last):
  File "/tmp/MySite/env/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/tmp/MySite/env/lib/python3.4/site-packages/djangocms_installer/main.py", line 37, in execute
    django.create_project(config_data)
  File "/tmp/MySite/env/lib/python3.4/site-packages/djangocms_installer/django/__init__.py", line 60, in create_project
    output = subprocess.check_output(cmd_args)
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['/tmp/MySite/env/bin/python3', '/tmp/MySite/env/bin/django-admin.py', 'startproject', 'mysite', '/tmp/MySite/mysite']' returned non-zero exit status 1
```
### Environment

* Python version: 3.4.2
* Django version: 1.8.18
* django CMS version: 3.4.5

**Comment by czpython** [comment]
Hello @pavelschon , please make sure to submit questions/support within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.

**Comment by pavelschon** [comment]
I disagree this is a user problem. It seems to be bug of install script.

**Comment by czpython** [comment]
Please have a look at the installation instructions in [our docs](http://docs.django-cms.org/en/latest/introduction/install.html#use-the-django-cms-installer).
The installer creates a virtual environment for you, also you need to add the `-f -p . mysite` options
