### ISSUE TITLE
Toolbar is not displayed properly

### ISSUE THREAD

**Issue by Julian28010** [divio/django-cms#6309]
### Summary

Hey guys,
I just upgraded my Django-CMS Version and then wanted to log in. After that I noticed, that the toolbar wasn't rendering properly and it looks like in the picture.

### Expected behaviour
Toolbar renders.

### Actual behaviour
Toolbar won't render properly.

### Environment

* Python version: 3.5
* Django version: 1.10.8
* django CMS version: 3.4.4
<img width="419" alt="capture" src="https://user-images.githubusercontent.com/26826135/37256856-bae26fc4-2560-11e8-9b9b-7da54c634cc2.PNG">

**Comment by Julian28010** [comment]
Also, if I want to edit the page it looks like this:
<img width="275" alt="capture" src="https://user-images.githubusercontent.com/26826135/37256981-0e6dd992-2563-11e8-9340-ccf78071a8fd.PNG">

**Comment by czpython** [comment]
Hello @Julian28010,
Looks like your static files are missing.
Did run `collectstatic`?

**Comment by Julian28010** [comment]
@czpython 
Thanks for your quick reply. Yeah, I did collect the successfully. Under the menu it displays the page as it is.

**Comment by Julian28010** [comment]
But that didn't help with the toolbar.

**Comment by Julian28010** [comment]
I had another instance of DjangoCMS (3.5.1) - my bad. But I got another error now where I don't know if it is still for the same problem I have:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/admin/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/admin/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/admin/.local/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/admin/.local/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/admin/.local/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'menus'

**Comment by czpython** [comment]
Hello @Julian28010, looks like you're django CMS 3.5 and have not ran the migrations.
As this is a project specific issue, I'm closing the ticket here but feel free to submit any further questions/support on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](https://www.django-cms.org/support) page.
