### ISSUE TITLE
Migrations not properly working?

### ISSUE THREAD

**Issue by Julian28010** [divio/django-cms#6310]
* Python version: 3.5.3
* Django version: 1.10.8
* django CMS version: 3.4.4

Hello guys,
I upgraded my DjangoCMS recently and it hasn't been working since then. Im getting a programmingError at runtime, which says:"column cms_page.path does not exist", which is right (I checked it). I did run the migrations with makemigrations and then migrate. It works but says: No changes detected. Full traceback:

`Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/admin/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/admin/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/admin/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/admin/.local/lib/python3.5/site-packages/cms/views.py", line 48, in details
    page = get_page_from_request(request, use_path=slug)
  File "/home/admin/.local/lib/python3.5/site-packages/cms/utils/page_resolver.py", line 120, in get_page_from_request
    page = get_page_from_path(path, preview, draft)
  File "/home/admin/.local/lib/python3.5/site-packages/cms/utils/page_resolver.py", line 76, in get_page_from_path
    return get_page_queryset_from_path(path, preview, draft).get()
  File "/home/admin/.local/lib/python3.5/site-packages/django/db/models/query.py", line 379, in get
    num = len(clone)
  File "/home/admin/.local/lib/python3.5/site-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/home/admin/.local/lib/python3.5/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/admin/.local/lib/python3.5/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/home/admin/.local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/home/admin/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/admin/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/admin/.local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/admin/.local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/admin/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column cms_page.path does not exist
LINE 1: SELECT "cms_page"."id", "cms_page"."path", "cms_page"."depth...
`

**Comment by czpython** [comment]
Hello @Julian28010,
As mentioned in https://github.com/divio/django-cms/issues/6309#issuecomment-372295831,
this is a project specific issue.

I saw your post in https://stackoverflow.com/questions/49237594/django-db-utils-programmingerror-column-cms-page-path-does-not-exist, I will get back to you as soon as I can there.
