### ISSUE TITLE
Foreign key error when upgrading from 3.3.0 to 3.5.x

### ISSUE THREAD

**Issue by AngellusMortis** [divio/django-cms#6338]
### Summary
As part of our upgrade of one of our sites, we upgraded from Django 1.8.x to Django 1.11.x, Django CMS 3.3.0 to Django CMS 3.5.x, and MySQL 14.14 to MariaDB 15.1. The cms.0018_pagenode migration is failing due to a foreign key issue. 

### Expected behavior
cms.0018_pagenode database migration to go through fine.

### Actual behavior
cms.0018_pagenode database migration fails.

Error from Django:
```
Applying cms.0018_pagenode...Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/srv/thesite/web/thesite/manage.py", line 15, in <module>
    main()
  File "/srv/thesite/web/thesite/manage.py", line 11, in main
    execute_from_command_line(sys.argv)
  File "/srv/thesite/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/thesite/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/thesite/venv/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/thesite/venv/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/srv/thesite/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/srv/thesite/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/srv/thesite/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/srv/thesite/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/srv/thesite/venv/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 93, in __exit__
    self.execute(sql)
  File "/srv/thesite/venv/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/srv/thesite/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/thesite/venv/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/thesite/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/thesite/venv/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/srv/thesite/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/srv/thesite/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1005, "Can't create table 'thesite.#sql-5a7_428' (errno: 150)")
```

Error from MySQL (generated from `SHOW ENGINE INNODB STATUS`):
```
------------------------
LATEST FOREIGN KEY ERROR
------------------------
180420 15:30:30 Error in foreign key constraint of table `thesite`.`cms_treenode`:
Alter  table `thesite`.`cms_treenode` with foreign key constraint failed. Referenced table `thesite`.`d
jango_site` not found in the data dictionary near ' FOREIGN KEY (`site_id`) REFERENCES `django_site` (`
id`)'.
```

### Environment
* Python version: 2.7.5
* Django version: 1.11.11
* django CMS version: 3.5.2 (happens on 3.5.0 and 3.5.1 as well)

**Comment by czpython** [comment]
Hello @AngellusMortis,
Are you also upgrading the django version?

**Comment by AngellusMortis** [comment]
Yes. Do the core Django migrations need to be ran first?

**Comment by AngellusMortis** [comment]
1.8 latest.

I just tried to apply the 4 Django migrations first and the issue still occurs. None of the other django.contrib apps had migrations from 1.8.x to 1.11.x. 

```
python -m thesite.manage migrate admin # applied admin -> 0002
python -m thesite.manage migrate sites # applied sites -> 0002
python -m thesite.manage migrate auth # applied auth -> 0007,0008
python -m thesite.manage migrate
```

I also tried to upgrade through 3.4.x first. I installed 3.4.6 with the all of the other packages the same, did a full migrate and then installed 3.5.x and did another full migrate and get the same error as above.

**Comment by czpython** [comment]
Thanks for the info.
Can you confirm that the `django_site` table exists after running `python -m thesite.manage migrate sites`?

**Comment by AngellusMortis** [comment]
Yes. I have verified the django_site table appears before and after the migrations run.

**Comment by AngellusMortis** [comment]
Ah! Found the issue. 

Like I said, this site is older. The database is a few years old. The older tables in the database (which `django_site` is one of the oldest tables in the database) are still MyISAM. Converting it to InnoDB solved the issue.
