### ISSUE TITLE
Creating the project The installation has failed.

### ISSUE THREAD

**Issue by MohitPrakashSharma** [divio/django-cms#6550]
Inimist-one@Inimist-one-PC MINGW64 ~/Desktop
$ djangocms myproject
Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the project
The installation has failed.

*****************************************************************

Check documentation at https://djangocms-installer.readthedocs.io

*****************************************************************

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python27\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python27\Scripts\djangocms.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\djangocms_installer\main.py", line 41, in execute
    django.setup_database(config_data)
  File "c:\python27\lib\site-packages\djangocms_installer\django\__init__.py", line 407, in setup_database
    command, env=env, stderr=subprocess.STDOUT
  File "c:\python27\lib\subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "c:\python27\lib\subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['c:\\python27\\python.exe', '-W', 'ignore', 'manage.py', 'migrate']' returned non-zero exit status 1.
* Python version:  3.7.0 
* Django version: (1, 11, 0, 'final', 1)
* django CMS version: 3.5.2

**Comment by maho-networks** [comment]
I recently had the same problem. With the --verbose mode I found out that this is a syntax error in the lib\site-packages\django\contrib\admin\widgets.py file.
See solution at github #28814 https://github.com/django/django/commit/931c60c5216bd71bc11f489e00e063331cf21f40

As far as I can see you just have to remove the comma at the end of the brackets in line 165 of widgets.py:
_related_url += '?' + '&amp;'.join('%s=%s' % (k, v) for k, v in params.items(),)_  <-remove comma
_related_url += '?' + '&amp;'.join('%s=%s' % (k, v) for k, v in params.items())_

**Comment by maho-networks** [comment]
nevertheless I was able to install and work with django-cms 3.5.2, django1.11 and python 3.7 after removing the comma.

additionally I also installed django-cms 3.5.2, django1.11 with python 3.6.7 and it works perfectly without removing the comma so I guess we should follow the official instructions.

thx for the advice jrief

**Comment by jrief** [comment]
@MohitPrakashSharma please close this issue
