### ISSUE TITLE
`AttributeError` from the Toolbar when saving plugins

### ISSUE THREAD

**Issue by marksweb** [divio/django-cms#6565]
### Summary

On saving a plugin `init_toolbar` is receiving a request which doesn't have a `session` attribute.

```bash
webapp_1_a97a7ddbcaa3 |   File "/usr/local/lib/python3.6/site-packages/cms/toolbar/toolbar.py", line 140, in __init__
webapp_1_a97a7ddbcaa3 |     self.init_toolbar(request, request_path=request_path)
webapp_1_a97a7ddbcaa3 |   File "/usr/local/lib/python3.6/site-packages/cms/toolbar/toolbar.py", line 193, in init_toolbar
webapp_1_a97a7ddbcaa3 |     if self.request.session.get('cms_toolbar_disabled', False):
webapp_1_a97a7ddbcaa3 | AttributeError: 'HttpRequest' object has no attribute 'session'
```

### Expected behaviour

Perform an attribute check to see if the request has a session before it's checked for `cms_toolbar_disabled`

### Actual behaviour

`init_toolbar` gets a request from `admin/cms/usersettings/cms-toolbar` and tries to get `cms_toolbar_disabled` from the session which causes an attribute error;
```python
    def init_toolbar(self, request, request_path=None):
        self.request = request
        self.is_staff = self.request.user.is_staff
        self.show_toolbar = self.is_staff or self.request.session.get('cms_edit', False)

        if self.request.session.get('cms_toolbar_disabled', False):
            self.show_toolbar = False
```

![screenshot 2018-11-23 at 12 21 08](https://user-images.githubusercontent.com/1461191/48943535-6d32c780-ef1b-11e8-80bb-bbaec5b50e82.png)

```bash
webapp_1_a97a7ddbcaa3 | INFO "POST /admin/aldryn_newsblog/article/edit-plugin/10/?cms_path=/news/testing-news/ HTTP/1.1" 200 19472
webapp_1_a97a7ddbcaa3 | INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3189
webapp_1_a97a7ddbcaa3 | Error while evaluating expression: not getattr(self.request, 'session')
webapp_1_a97a7ddbcaa3 | Traceback (most recent call last):
webapp_1_a97a7ddbcaa3 |   File "/opt/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 43, in handle_breakpoint_condition
webapp_1_a97a7ddbcaa3 |     return eval(condition, new_frame.f_globals, new_frame.f_locals)
webapp_1_a97a7ddbcaa3 |   File "<string>", line 1, in <module>
webapp_1_a97a7ddbcaa3 | AttributeError: 'HttpRequest' object has no attribute 'session'
webapp_1_a97a7ddbcaa3 | INFO "GET /news/testing-news/?edit HTTP/1.1" 200 68031
webapp_1_a97a7ddbcaa3 | ERROR Internal Server Error: /admin/cms/usersettings/cms-toolbar/
webapp_1_a97a7ddbcaa3 | Traceback (most recent call last):
webapp_1_a97a7ddbcaa3 |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
webapp_1_a97a7ddbcaa3 |     response = get_response(request)
webapp_1_a97a7ddbcaa3 |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
webapp_1_a97a7ddbcaa3 |     response = self.process_exception_by_middleware(e, request)
webapp_1_a97a7ddbcaa3 |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
webapp_1_a97a7ddbcaa3 |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
webapp_1_a97a7ddbcaa3 |   File "/usr/local/lib/python3.6/site-packages/cms/admin/settingsadmin.py", line 28, in wrapper
webapp_1_a97a7ddbcaa3 |     return self.admin_site.admin_view(view)(*args, **kwargs)
webapp_1_a97a7ddbcaa3 |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
webapp_1_a97a7ddbcaa3 |     response = view_func(request, *args, **kwargs)
webapp_1_a97a7ddbcaa3 |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
webapp_1_a97a7ddbcaa3 |     response = view_func(request, *args, **kwargs)
webapp_1_a97a7ddbcaa3 |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 224, in inner
webapp_1_a97a7ddbcaa3 |     return view(request, *args, **kwargs)
webapp_1_a97a7ddbcaa3 |   File "/usr/local/lib/python3.6/site-packages/cms/admin/settingsadmin.py", line 99, in get_toolbar
webapp_1_a97a7ddbcaa3 |     request.toolbar = CMSToolbar(request, request_path=origin_url.path, _async=True)
webapp_1_a97a7ddbcaa3 |   File "/usr/local/lib/python3.6/site-packages/cms/toolbar/toolbar.py", line 140, in __init__
webapp_1_a97a7ddbcaa3 |     self.init_toolbar(request, request_path=request_path)
webapp_1_a97a7ddbcaa3 |   File "/usr/local/lib/python3.6/site-packages/cms/toolbar/toolbar.py", line 193, in init_toolbar
webapp_1_a97a7ddbcaa3 |     if self.request.session.get('cms_toolbar_disabled', False):
webapp_1_a97a7ddbcaa3 | AttributeError: 'HttpRequest' object has no attribute 'session'
```

I'm happy to setup a PR for this.

### Environment

* Python version: 3.6.7
* Django version: 1.11.15
* django CMS version: 3.5.3

**Comment by marksweb** [comment]
Discovered this was caused by a monkey patch which is intended for use in our celery workflow for using URLs.

```python
# Monkey-patch WSGIRequest to allow it to be pickled (when sent to a celery
# task, etc.)
METACOPY = ['HTTP_HOST', 'REMOTE_ADDR', 'HTTPS', 'SERVER_NAME', 'SERVER_PORT']


def __reduce__(self):
    from authentication.models import AnonymousUser
    from django.http import HttpRequest

    request_dict = {
        'META': dict([
            (k, self.META[k]) for k in METACOPY
            if k in self.META and
            isinstance(self.META[k], (int, str, unicode, bool))
        ]),
        'POST': self.POST,
        'GET': self.GET,
        'user': self.user if hasattr(self, 'user') else AnonymousUser(),
        'path': self.path
    }
    return HttpRequest, (), request_dict


WSGIRequest.__reduce__ = __reduce__
```

The call for `request = copy.copy(request)` before the toolbar is initialised caused the monkey `__reduce__` method to come into effect & removed the `session` attribute of the request.
