### ISSUE TITLE
test suite state

### ISSUE THREAD

**Issue by benzkji** [divio/django-cms#6686]
### Summary

Tests (./manage.py test) are failing for current develop, but also for 3.6.0, 3.5.3.

3.4.6 is ok. #3684 is closed, but for me, testing django-cms is still error prone? How to make this situation better?

### Expected behaviour

Passes tests. Also, question, is there a possibility to easily run all combinations of environments at once, like for example with `tox`?

### Actual behaviour

```
HEAD is now at b2b35ca9d Release 3.6.0 (#6606)
(django-cms) --- open/django-cms » ./manage.py test
Creating test database for alias 'default'...
System check identified some issues:

WARNINGS:
?: (1_10.W001) The MIDDLEWARE_CLASSES setting is deprecated in Django 1.10 and the MIDDLEWARE setting takes precedence. Since you've set MIDDLEWARE, the value of MIDDLEWARE_CLASSES is ignored.

System check identified 1 issue (0 silenced).
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F...........................................................FF...................................
Publishing public drafts....
1.	*  home [1]
2.	*  página 1 [3]
3.	*  página 2 [5]

========================================

Total:     3
Published: 3
.......................................................FF.......................................................................................................................No handlers could be found for logger "menus"
............................................s..............................................................................................................................................Es..................................................
======================================================================
ERROR: test_html (cms.tests.test_docs.DocsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/benzkji/Development/open/django-cms/cms/tests/test_docs.py", line 62, in test_html
    status=status,
  File "/home/benzkji/.virtualenvs/django-cms/local/lib/python2.7/site-packages/sphinx/application.py", line 163, in __init__
    self.setup_extension(extension)
  File "/home/benzkji/.virtualenvs/django-cms/local/lib/python2.7/site-packages/sphinx/application.py", line 473, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/home/benzkji/.virtualenvs/django-cms/local/lib/python2.7/site-packages/sphinxcontrib/spelling/__init__.py", line 5, in <module>
    from .builder import SpellingBuilder
  File "/home/benzkji/.virtualenvs/django-cms/local/lib/python2.7/site-packages/sphinxcontrib/spelling/builder.py", line 23, in <module>
    logger = logging.getLogger(__name__)
AttributeError: 'module' object has no attribute 'getLogger'

======================================================================
FAIL: test_menu_tree_without_soft_root (cms.tests.test_menu.AdvancedSoftrootTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/benzkji/Development/open/django-cms/cms/tests/test_menu.py", line 1358, in test_menu_tree_without_soft_root
    self.assertTreeQuality(hard_root, mock_tree)
  File "/home/benzkji/Development/open/django-cms/cms/tests/test_menu.py", line 1281, in assertTreeQuality
    self.assertEqual(len(a), len(b), msg)
AssertionError: 4 != 1 with [<Navigation Node: top>, <Navigation Node: sample root page>, <Navigation Node: sample settings page>, <Navigation Node: sample account page>], [<AttributeObject: {'level': 0, 'children': [<AttributeObject: {'level': 1, 'children': [<AttributeObject: {'level': 2, 'children': [<AttributeObject: {'level': 3, 'children': [<AttributeObject: {'level': 4, 'children': [<AttributeObject: {'level': 5, 'children': [], 'title': 'ddd'}>], 'title': 'ccc'}>], 'title': '111'}>, <AttributeObject: {'level': 3, 'children': [], 'title': '222'}>], 'title': 'aaa'}>, <AttributeObject: {'level': 2, 'children': [], 'title': 'bbb'}>], 'title': 'root'}>], 'title': 'top'}>]

======================================================================
FAIL: test_basic_home (cms.tests.test_menu.SoftrootTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/benzkji/Development/open/django-cms/cms/tests/test_menu.py", line 1980, in test_basic_home
    self.assertEqual(len(nodes), 1)
AssertionError: 4 != 1

======================================================================
FAIL: test_basic_people (cms.tests.test_menu.SoftrootTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/benzkji/Development/open/django-cms/cms/tests/test_menu.py", line 2116, in test_basic_people
    self.assertEqual(len(nodes), 1)
AssertionError: 4 != 1

======================================================================
FAIL: test_public_menu_anonymous_user (cms.tests.test_menu_page_viewperm.ViewPermissionComplexMenuAllNodesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/benzkji/Development/open/django-cms/cms/tests/test_menu_page_viewperm.py", line 324, in test_public_menu_anonymous_user
    self.assertEqual(len(nodes), 4)
AssertionError: 8 != 4

======================================================================
FAIL: test_public_pages_anonymous_norestrictions (cms.tests.test_menu_page_viewperm.ViewPermissionComplexMenuAllNodesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/benzkji/Development/open/django-cms/cms/tests/test_menu_page_viewperm.py", line 299, in test_public_pages_anonymous_norestrictions
    self.assertEqual(len(nodes), len(all_pages))
AssertionError: 25 != 21

----------------------------------------------------------------------
Ran 1113 tests in 146.138s

FAILED (failures=5, errors=1, skipped=2)
Destroying test database for alias 'default'...
 ```

### Environment

* Python version: 2.7
* Django version: 1.11
* django CMS version: 3.4.6, 3.5.3, 3.6.0

**Comment by benzkji** [comment]
still exactly the same, with current develop? did I miss anything when setting up things?

**Comment by FinalAngel** [comment]
tests are working "in general". That being said, dependencies and deprecations happen all the time and thus the tests need to be adapted. E.g. EOL of Python 2.7 or packages not supporting Django 1.11 anymore.

Thus the tests need to be adapted/fixed from time to time. Most will be fixed after today though.
