### ISSUE TITLE
Pip install django-cms not installing properly 

### ISSUE THREAD

**Issue by memetics19** [divio/django-cms#6807]
whenever I try to installing django-cms this error will be popped up.

```
$ pip install django-cms
Collecting django-cms
  Using cached django_cms-3.7.1-py2.py3-none-any.whl (2.7 MB)
Collecting Django<3.0,>=1.11
  Downloading Django-2.2.10-py3-none-any.whl (7.5 MB)
     |█████                           | 1.2 MB 24 kB/s eta 0:04:15ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 425, in _error_catcher
    yield
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "c:\users\shreeda\anaconda3\lib\http\client.py", line 457, in read
    n = self.readinto(b)
  File "c:\users\shreeda\anaconda3\lib\http\client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "c:\users\shreeda\anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\users\shreeda\anaconda3\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\shreeda\anaconda3\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
    status = self.run(options, args)
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_internal\commands\install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_internal\legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_internal\legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_internal\legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 482, in prepare_linked_requirement
    hashes=hashes,
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 287, in unpack_url
    hashes=hashes,
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 159, in unpack_http_url
    link, downloader, temp_dir.path, hashes
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 303, in _download_http_url
    for chunk in download.chunks:
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_internal\utils\ui.py", line 160, in iter
    for x in it:
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_internal\network\utils.py", line 39, in response_chunks
    decode_content=False,
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\users\shreeda\anaconda3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Shreeda\Documents\astaqc\research\cms\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

**Comment by Par9890** [comment]
That's the exact issue that am having. Is there a solution yet?

**Comment by memetics19** [comment]
I think I might have the solution. Try `pip install djangocms-installer`
