### ISSUE TITLE
3.7.2 version:  ImportError: cannot import name 'python_2_unicode_compatible' from 'cms.utils.compat.dj'

### ISSUE THREAD

**Issue by sarkaaa** [divio/django-cms#6846]
## Description

New version of django-cms fails when commands below are run. I can not see this behavior in previous version 3.7.1.

## Steps to reproduce

1. pipenv install
2. `python manage.py makemigrations` or `python manage.py collectstatic`

## Expected behaviour

`python manage.py collecstatic` or `python manage.py makemigrations` passes

## Actual behaviour

Fails with error. Log from Heroku app.
```
-----> Python app detected
-----> Installing dependencies with Pipenv 2018.5.18…
       Installing dependencies from Pipfile.lock (9c6d0d)…
-----> Installing SQLite3
-----> $ python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "manage.py", line 21, in <module>
           main()
         File "manage.py", line 17, in main
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
           django.setup()
         File "/app/.heroku/python/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
           apps.populate(settings.INSTALLED_APPS)
         File "/app/.heroku/python/lib/python3.7/site-packages/django/apps/registry.py", line 112, in populate
           app_config.import_models()
         File "/app/.heroku/python/lib/python3.7/site-packages/django/apps/config.py", line 198, in import_models
           self.models_module = import_module(models_module_name)
         File "/app/.heroku/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
         File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
         File "<frozen importlib._bootstrap>", line 983, in _find_and_load
         File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
         File "<frozen importlib._bootstrap_external>", line 728, in exec_module
         File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
         File "/app/.heroku/python/lib/python3.7/site-packages/djangocms_column/models.py", line 6, in <module>
           from cms.utils.compat.dj import python_2_unicode_compatible
       ImportError: cannot import name 'python_2_unicode_compatible' from 'cms.utils.compat.dj' (/app/.heroku/python/lib/python3.7/site-packages/cms/utils/compat/dj.py)
```

## Additional information
It happens when Heroku app is built and I encountered this error also on Fedora. If you need additional information let me know.

**Comment by chase-meyer** [comment]
go through `/app/.heroku/python/lib/python3.7/site-packages/djangocms_column/models.py` and remove every line with `python_2_unicode_compatible` assuming your using python3 [here](https://consideratecode.com/2017/08/25/what-does-python_2_unicode_compatible-do/) It will run after your remove this.

**Comment by vakorol** [comment]
I experience this with Python 3.8 and DjangoCMS 3.7.2. The issue does not reproduce with DjangoCMS 3.7.1.
This issue is blocking me from upgrading.

**Comment by vakorol** [comment]
Update:
Version 3.7.2 seems to work without @djangocms_column@.
Both cases tested with Django 2.2.

**Comment by oliwarner** [comment]
Seeing the same with djangocms-teaser

**Comment by FinalAngel** [comment]
please raise these issues in the respective addons (djangocms-column or djangocms-teaser). These are deprecation issues.
