### ISSUE TITLE
I am quite new to django i coonected mongodb to django using djongo...it worked well for few days ,then this error occured

### ISSUE THREAD

**Issue by niteshballa** [divio/django-cms#6877]
Apply all migrations: admin, auth, contenttypes, pages, sessions
Running migrations:
  Applying pages.0001_initial...This version of djongo does not support "NULL, NOT NULL column validation check" fully. Visit https://www.patreon.com/nesdis
Traceback (most recent call last):
  File "C:\Users\Personal\Envs\projects\lib\site-packages\djongo\sql2mongo\query.py", line 856, in parse
    return handler(self, statement)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\djongo\sql2mongo\query.py", line 897, in _create
    query = CreateQuery(self.db, self.connection_properties, sm, self._params)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\djongo\sql2mongo\query.py", line 645, in __init__
    super().__init__(*args)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\djongo\sql2mongo\query.py", line 84, in __init__
    super().__init__(*args)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\djongo\sql2mongo\query.py", line 62, in __init__
    self.parse()
  File "C:\Users\Personal\Envs\projects\lib\site-packages\djongo\sql2mongo\query.py", line 729, in parse
    self._create_table(statement)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\djongo\sql2mongo\query.py", line 704, in _create_table
    self.db[table].create_index(field, unique=True, name='__primary_key__')
  File "C:\Users\Personal\Envs\projects\lib\site-packages\pymongo\collection.py", line 1995, in create_index
    self.__create_index(keys, kwargs, session, **cmd_options)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\pymongo\collection.py", line 1890, in __create_index
    self._command(
  File "C:\Users\Personal\Envs\projects\lib\site-packages\pymongo\collection.py", line 235, in _command
    return sock_info.command(
  File "C:\Users\Personal\Envs\projects\lib\site-packages\pymongo\pool.py", line 603, in command
    return command(self.sock, dbname, spec, slave_ok,
  File "C:\Users\Personal\Envs\projects\lib\site-packages\pymongo\network.py", line 165, in command
    helpers._check_command_response(
  File "C:\Users\Personal\Envs\projects\lib\site-packages\pymongo\helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: 16: Resource device

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Personal\Envs\projects\lib\site-packages\djongo\cursor.py", line 51, in execute
    self.result = Query(
  File "C:\Users\Personal\Envs\projects\lib\site-packages\djongo\sql2mongo\query.py", line 783, in __init__
    self._query = self.parse()
  File "C:\Users\Personal\Envs\projects\lib\site-packages\djongo\sql2mongo\query.py", line 868, in parse
    raise exe from e
djongo.exceptions.SQLDecodeError:

        Keyword: None
        Sub SQL: None
        FAILED SQL: CREATE TABLE "pages_weeksuggestions" ("id" int NOT NULL PRIMARY KEY AUTOINCREMENT, "title" string NOT NULL, "link" string NOT 
NULL, "date" string NOT NULL, "image" string NOT NULL)
        Params: None
        Version: 1.3.3

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\core\management\commands\migrate.py", line 231, in handle
    post_migrate_state = executor.migrate(
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\db\migrations\executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\db\migrations\operations\models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\db\backends\base\schema.py", line 324, in create_model
    self.execute(sql, params or None)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\db\backends\base\schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Personal\Envs\projects\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql)
  File "C:\Users\Personal\Envs\projects\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
django.db.utils.DatabaseError

 I dont know how this occured

i want to migrate all the models

**Comment by FinalAngel** [comment]
Hello 👋 , please ask your question inside our user group: https://groups.google.com/g/django-cms
