### ISSUE TITLE
not able to create superuser for django admin

### ISSUE THREAD

**Issue by bhandaribhumin** [divio/django-cms#6899]
## Description

when I try to create superuser for admin using **python manage.py createsuperuser** get  some error 

## Error

```
tutorial-env) (base) Bhumins-MacBook:projx-backend bhuminbhandari$ python manage.py createsuperuser
Email: bhumin@gmail.com
Password: 
Password (again): 
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/bhuminbhandari/envs/tutorial-env/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/bhuminbhandari/envs/tutorial-env/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/bhuminbhandari/envs/tutorial-env/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/bhuminbhandari/envs/tutorial-env/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/Users/bhuminbhandari/envs/tutorial-env/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/bhuminbhandari/envs/tutorial-env/lib/python3.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 189, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/Users/bhuminbhandari/Desktop/Projects/python/projx-backend/projx/login_app/models.py", line 23, in create_superuser
    is_acive=True
  File "/Users/bhuminbhandari/envs/tutorial-env/lib/python3.7/site-packages/django/db/models/base.py", line 500, in __init__
    raise TypeError("%s() got an unexpected keyword argument '%s'" % (cls.__name__, kwarg))
TypeError: User() got an unexpected keyword argument 'is_acive'
```

**Comment by FinalAngel** [comment]
@bhandaribhumin please provide additional information like Django/Python/django CMS version as stated when creating the issue.

**Comment by bhandaribhumin** [comment]
@FinalAngel thanks for reply. problem is in my code so I solved it sorry for creating issue.

**Comment by FinalAngel** [comment]
thanks for the feedback @bhandaribhumin
